//! Bakes a manifest of the engine asset library (`<workspace>/assets`) into the
//! crate so the **web build** can enumerate it.
//!
//! On native, `discovery::list_assets` walks the filesystem. The browser has no
//! filesystem, so the wasm path reads this compile-time manifest instead —
//! otherwise the spawn/shader catalogs come up empty on web (the `.usda`/`.wgsl`
//! files ship in the bundle but can't be `readdir`'d). Only the catalog
//! extensions (`usda`, `wgsl`) are baked, keeping the manifest small.
//!
//! Build scripts run at compile time on the *host*, never on wasm, so the
//! workspace `disallowed_methods` ban on `std::fs` (a wasm-runtime foot-gun)
//! does not apply here. `clippy.toml`'s header already names `build.rs` as
//! exempt; cargo has no path-scoped lint config, so the exemption has to be
//! written out.
#![allow(clippy::disallowed_methods)]

use std::path::Path;

const BAKED_EXTS: &[&str] = &["usda", "wgsl"];

fn main() {
    // This crate is `<workspace>/crates/lunco-assets`; the engine asset library
    // is `<workspace>/assets` — the same dir the native scanner walks at
    // runtime (`<cwd>/assets`).
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../../assets");

    let mut rels: Vec<String> = Vec::new();
    if assets_dir.is_dir() {
        walk(&assets_dir, &assets_dir, &mut rels);
    } else {
        println!(
            "cargo:warning=lunco-assets: assets dir not found at {} — web asset manifest will be empty",
            assets_dir.display()
        );
    }
    rels.sort();
    rels.dedup();

    let mut src = String::from(
        "// @generated by build.rs — do not edit. Engine asset library paths\n\
         // (relative to the default/`lunco://` source) for the web build.\n\
         pub static BAKED_ASSET_RELS: &[&str] = &[\n",
    );
    for r in &rels {
        src.push_str("    \"");
        src.push_str(&r.replace('\\', "/").replace('"', "\\\""));
        src.push_str("\",\n");
    }
    src.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_asset_manifest.rs"), src).unwrap();

    println!("cargo:rerun-if-changed={}", assets_dir.display());
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<String>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            match p.file_name().and_then(|s| s.to_str()) {
                Some(n) if n.starts_with('.') || n == "target" => continue,
                _ => {
                    println!("cargo:rerun-if-changed={}", p.display());
                    walk(base, &p, out);
                }
            }
        } else {
            let keep = p
                .extension()
                .and_then(|s| s.to_str())
                .is_some_and(|ext| BAKED_EXTS.contains(&ext));
            if keep {
                if let Ok(rel) = p.strip_prefix(base) {
                    if let Some(rel_s) = rel.to_str() {
                        out.push(rel_s.replace('\\', "/"));
                    }
                }
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }
}
