//! UI-facing accessors for the shared Modelica document registry.
//!
//! The registry itself is the generic [`lunco_doc_bevy::DocumentRegistry`].
//! This module only supplies the concrete Modelica type and derives display
//! facts needed by workbench panels; it does not own document lifecycle.

use bevy::prelude::World;
use lunco_doc::DocumentId;
use lunco_doc_bevy::DocumentRegistry;
use lunco_modelica_document::ModelicaDocument;

/// The shared Modelica document registry used by UI systems.
pub(crate) type ModelicaDocuments = DocumentRegistry<ModelicaDocument>;

/// Whether a document was generated by a runtime projection.
pub(crate) fn is_generated_document(document: &ModelicaDocument) -> bool {
    lunco_modelica_runtime::generated_source::is_generated_origin(document.origin())
}

/// Detected top-level model name for a document.
pub(crate) fn detected_name_for(world: &World, doc: DocumentId) -> Option<String> {
    lunco_modelica_core::sim_default::default_simulation_class(world, doc)
}

/// Read-only flag for a document.
pub(crate) fn read_only_for(world: &World, doc: DocumentId) -> bool {
    world
        .resource::<ModelicaDocuments>()
        .host(doc)
        .map(|host| host.document().is_read_only())
        .unwrap_or(false)
}

/// Display name for a document.
pub(crate) fn display_name_for(world: &World, doc: DocumentId) -> Option<String> {
    world
        .resource::<ModelicaDocuments>()
        .host(doc)
        .map(|host| host.document().origin().display_name())
}
