//! # Surface Mobility & Traction Physics
//!
//! This crate implements the core physics models for planetary rovers and 
//! surface exploration vehicles. 
//!
//! ## The "Why": Raycast-Based Ground Interaction
//! Traditional mesh-to-mesh collision for wheels is computationally expensive 
//! and prone to "snagging" on terrain geometry. We use a **Raycast Wheel** 
//! model to provide a stable, high-performance alternative:
//! 1. **Suspension Logic**: An emulated spring-damper system computes normal 
//!    forces based on ray length, preventing high-frequency jitter.
//! 2. **Traction Physics**: Lateral and longitudinal friction are applied 
//!    at the ray's contact point, allowing for complex skid and slip behaviors 
//!    without the overhead of continuous contact manifolds.
//! 3. **Numeric Stability**: By projecting a single ray, we ensure the wheel 
//!    always "floats" at the correct elevation, even on highly irregular 
//!    procedural terrain.
//!
//! ## Control Mixing Models
//! The crate supports hotswappable steering architectures:
//! - **Differential (Skid) Drive**: Common for heavy loaders and excavators; 
//!   turns by varying velocity between left and right tracks.
//! - **Ackermann Steering**: Standard for high-speed mobility; pivots leading 
//!   wheels to maintain a common center of rotation, reducing tire scrub.

use bevy::prelude::*;
use bevy::math::DVec3;
use avian3d::prelude::*;
use lunco_core::architecture::DigitalPort;
use lunco_core::RoverVessel;
use lunco_core::{Command, on_command, register_commands};
use lunco_fsw::FlightSoftware;

mod wheel_spin;
use wheel_spin::update_wheel_spin;

/// Manages the integration of mobility physics and control observers.
pub struct LunCoMobilityPlugin;

impl Plugin for LunCoMobilityPlugin {
    fn build(&self, app: &mut App) {
        app.register_type::<Suspension>()
           .register_type::<DifferentialDrive>()
           .register_type::<AckermannSteer>()
           .register_type::<WheelRaycast>()
           .add_systems(FixedUpdate, (
               suspension_system,
               apply_wheel_suspension,
               apply_wheel_drive,
               apply_wheel_steering,
               update_wheel_spin,
           ).chain()
           // Read `PhysicalPort` AFTER the DAC has propagated this tick's
           // `DigitalPort` command into it (same fixed tick), so actuation isn't
           // delayed an extra tick. See `lunco_core::ControlDacSet`.
           .after(lunco_core::ControlDacSet)
           .run_if(
               // Run wherever physics is live. On a pure client this used to be
               // skipped entirely (replicated rovers are server-authoritative
               // proxies); predict-own now lets the client locally simulate the
               // ONE rover it possesses. We don't gate by role here — the owned
               // rover is the only `Dynamic` chassis on a client (every other
               // replicated body is pinned `Kinematic` by `force_kinematic_proxies`),
               // and the per-chassis `RigidBody::Kinematic` guard inside each wheel
               // system already skips those. So host/standalone simulate every
               // rover (unchanged) and a client simulates only its owned one.
               |tw: Res<lunco_core::TimeWarpState>| tw.physics_enabled));

        // TEMP DIAGNOSTIC (forward+turn jitter localization) — remove once resolved.
        app.init_resource::<WheelDriveDebug>()
           .add_systems(FixedUpdate, debug_log_wheel_drive.after(PhysicsSystems::Writeback));

        // Register all typed commands (generated by register_commands! macro)
        register_all_commands(app);
    }
}

/// Max per-wheel drive force as a multiple of that wheel's normal force
/// (`throttle · N · this`). Caps traction to a fraction of the contact's
/// grip — i.e. how much the tyre can push before the friction cone limits it.
const DEFAULT_DRIVE_FORCE_PER_NORMAL: f64 = 2.0;
/// Default for [`WheelRaycast::contact_grip_stiffness`] (N·s/m) when USD does not
/// author `lunco:contactGripStiffness`.
const DEFAULT_CONTACT_GRIP_STIFFNESS: f64 = 50.0;

/// A high-performance wheel model using emulated suspension rays.
///
/// **Theory**: Instead of a physical collider, this component projects a ray
/// downwards. The resulting distance is used to solve the spring-damper
/// equation, simulating the behavior of a physical tire and strut.
#[derive(Component, Debug, Clone, Reflect)]
#[reflect(Component, Default)]
pub struct WheelRaycast {
    /// Port mapping for suspension telemetry.
    pub suspension_port: Entity,
    /// Port mapping for drive torque actuation.
    pub drive_port: Entity,
    /// Port mapping for steering angle actuation.
    pub steer_port: Entity,
    /// Length of the suspension at rest in meters.
    pub rest_length: f64,
    /// Hooke's Law spring constant (Stiffness in N/m).
    pub spring_k: f64,
    /// Damping coefficient to suppress oscillations (Ns/m).
    pub damping_c: f64,
    /// Radius of the tire (effectively the minimum offset from ground).
    pub wheel_radius: f64,
    /// Y-offset of the ray origin relative to the wheel transform (meters).
    /// Used for visual wheel positioning.
    pub ray_origin_y: f64,
    /// Entity for the visual mesh to be transformed.
    pub visual_entity: Option<Entity>,
    /// Resultant normal force from the last physics tick, used for friction calculations.
    pub last_normal_force: f64,
    /// Accumulated rolling angle of the tire about its axle (radians, wrapped to 0..2π).
    /// Drives the visible spin of the wheel mesh.
    pub spin_angle: f64,
    /// Angular velocity of the tire about its axle (rad/s). State for the spin
    /// integrator — couples to ground speed when rolling, diverges under
    /// wheelspin/skid, and free-runs (driven by torque vs bearing drag) in the air.
    pub spin_velocity: f64,
    /// Tire mass in kg (USD `physics:mass`). Sets the rotational inertia
    /// `½·m·r²` that resists changes in spin (unless `moment_of_inertia` is set).
    pub mass: f64,
    /// Explicit axle moment of inertia in kg·m² (USD `physxVehicleWheel:moi`).
    /// When `> 0` it overrides the mass-derived `½·m·r²`.
    pub moment_of_inertia: f64,
    /// Peak motor drive torque about the axle in N·m. Derived from the USD
    /// motor curve (`motorPower / ω_noLoad`).
    pub drive_torque_max: f64,
    /// Axle bearing/rolling drag in N·m·s. Derived so the free (airborne) spin
    /// terminates at the motor's no-load speed (`drive_torque_max / ω_noLoad`).
    pub bearing_damping: f64,
    /// Tire-ground friction coefficient (USD `lunco:frictionCoefficient`).
    /// Caps the traction torque at `μ·N`, above which the tire breaks loose.
    pub friction_mu: f64,
    /// Longitudinal slip stiffness in N per m/s of contact slip. Governs how
    /// hard the tire grips toward `v/r` before saturating at the friction limit.
    pub slip_stiffness: f64,
    /// Chassis-contact grip stiffness in N·s/m: the slope of the contact
    /// friction force vs slip velocity in `apply_wheel_drive`, before it
    /// saturates at the Coulomb cone `μ·N`. Distinct from `slip_stiffness`
    /// (which is the *axle* spin model in `update_wheel_spin`). USD:
    /// `lunco:contactGripStiffness`.
    pub contact_grip_stiffness: f64,
    /// Peak brake torque about the axle in N·m. When it exceeds the available
    /// traction torque the wheel locks and skids.
    pub brake_torque_max: f64,
}

impl Default for WheelRaycast {
    fn default() -> Self {
        Self {
            suspension_port: Entity::PLACEHOLDER,
            drive_port: Entity::PLACEHOLDER,
            steer_port: Entity::PLACEHOLDER,
            rest_length: 0.4,
            spring_k: 8000.0,
            damping_c: 2800.0,
            wheel_radius: 0.4,
            ray_origin_y: 0.0,
            visual_entity: None,
            last_normal_force: 0.0,
            spin_angle: 0.0,
            spin_velocity: 0.0,
            mass: 25.0,
            moment_of_inertia: 0.0,
            drive_torque_max: 220.0,
            bearing_damping: 2.5,
            friction_mu: 1.0,
            slip_stiffness: 8000.0,
            contact_grip_stiffness: DEFAULT_CONTACT_GRIP_STIFFNESS,
            brake_torque_max: 600.0,
        }
    }
}

impl WheelRaycast {
    /// The tire's local roll about its axle as a quaternion.
    ///
    /// This is the single source of truth for the wheel's rotation — the visual
    /// mesh is rebuilt from it each tick, and any other system (telemetry,
    /// odometry, networking, a drivetrain model) can read the same orientation
    /// without inspecting the render transform. Built fresh from the wrapped
    /// `spin_angle`, so it never accumulates floating-point drift and is
    /// continuous across the 2π wrap (a 2π quaternion is identity).
    #[inline]
    pub fn spin_quat(&self) -> Quat {
        Quat::from_rotation_x(-(self.spin_angle as f32))
    }

    /// The tire's angular velocity about its axle in rad/s (signed: positive is
    /// forward roll). Real physical state — e.g. wheel-encoder odometry can
    /// integrate ground distance as `spin_velocity * wheel_radius`.
    #[inline]
    pub fn axle_angular_velocity(&self) -> f64 {
        self.spin_velocity
    }

    /// Surface (contact-patch) speed implied by the current spin, `ω · r` in m/s.
    /// Compare against chassis ground speed to recover the slip ratio.
    #[inline]
    pub fn surface_speed(&self) -> f64 {
        self.spin_velocity * self.wheel_radius
    }

    /// Rotational inertia of the tire about its axle in kg·m². Uses the
    /// USD-authored `physxVehicleWheel:moi` when set, else the solid-disk
    /// estimate `½·m·r²` from mass and radius.
    #[inline]
    pub fn axle_inertia(&self) -> f64 {
        if self.moment_of_inertia > 0.0 {
            return self.moment_of_inertia.max(1e-4);
        }
        let r = self.wheel_radius.max(1e-3);
        (0.5 * self.mass * r * r).max(1e-4)
    }
}

/// System solving the vertical suspension dynamics.
///
/// **Logic**: Performs a ray-world intersection check. If a hit is detected
/// within the suspension travel range, it applies an upward force to the
/// parent chassis based on the compression distance and relative velocity.
///
/// **Suspension model**: Spring-damper using Hooke's law:
/// `F = k * compression + c * relative_velocity`
/// Damping is bidirectional — it resists both compression and extension
/// to prevent oscillation. Force is only applied upward (along hit normal)
/// to avoid pulling the chassis into the ground.
///
/// **Geometry**: The ray origin is at the wheel entity transform (the
/// suspension mount point on the chassis). The ray points straight down.
/// `hit_distance` = distance from mount to ground. When `hit_distance <
/// rest_length` the spring is compressed. The wheel visual is positioned at
/// `ground_y + wheel_radius` so the tire rests on the terrain surface.
fn apply_wheel_suspension(
    mut q_wheels: Query<(
        &mut WheelRaycast,
        &RayHits,
        &Transform,
        &ChildOf,
    )>,
    mut q_chassis: Query<(Forces, &RigidBody), With<RoverVessel>>,
    mut q_visual: Query<&mut Transform, (Without<WheelRaycast>, Without<RoverVessel>)>,
) {
    for (mut wheel, hits, wheel_tf, parent) in q_wheels.iter_mut() {
        let parent_entity = parent.parent();
        if let Ok((mut forces, body)) = q_chassis.get_mut(parent_entity) {
            // Skip forces if body is kinematic (e.g. during gizmo drag)
            if matches!(body, RigidBody::Kinematic) {
                wheel.last_normal_force = 0.0;
                continue;
            }
            let world_pos = forces.position().0 + forces.rotation().0 * wheel_tf.translation.as_dvec3();

            if let Some(hit) = hits.iter_sorted().next() {
                let distance = hit.distance;
                if distance < wheel.rest_length {
                    // Suspension is compressed: apply spring-damper force.
                    let compression = wheel.rest_length - distance;
                    let spring_force_mag = compression * wheel.spring_k;

                    // Damping calculation based on relative normal velocity.
                    // Positive relative_vel = wheel moving toward ground (compressing).
                    // Negative relative_vel = wheel moving away from ground (extending).
                    // Damping always opposes motion.
                    let ray_dir_world = forces.rotation().0 * Vec3::NEG_Y.as_dvec3();
                    let lin_vel = forces.linear_velocity();
                    let ang_vel = forces.angular_velocity();
                    let velocity_at_wheel = lin_vel + ang_vel.cross(world_pos - forces.position().0);
                    let relative_vel = velocity_at_wheel.dot(ray_dir_world);

                    // Damping resists normal motion, but bounded to ±spring so the
                    // contact force stays in [0, 2·spring] WITHOUT a hard `.max(0)`
                    // cliff. The old `(spring + c·v).max(0)` was one-sided: on fast
                    // rebound `c·v` went strongly negative, the total clamped to 0,
                    // and the rebound half-cycle got ZERO damping → an undamped
                    // suspension limit-cycle (tick-period normal-force bounce that
                    // coupled into chassis yaw as the residual jitter). Unbounded `c·v`
                    // also spiked the normal force on hard hits (huge transients).
                    // Clamping the damping term fixes both: damping acts on both
                    // half-cycles, and the force can't blow up.
                    let damping_force_mag =
                        (relative_vel * wheel.damping_c).clamp(-spring_force_mag, spring_force_mag);
                    let total_force_mag = spring_force_mag + damping_force_mag;

                    let force_vec = hit.normal * total_force_mag;
                    forces.apply_force_at_point(force_vec, world_pos);
                    wheel.last_normal_force = total_force_mag;

                    // Position the wheel visual on the ground.
                    //
                    // The visual is now always a CHILD of the wheel entity
                    // (see `setup_raycast_wheel` in lunco-usd-sim) — its
                    // local Y is relative to the wheel mount point, not the
                    // chassis. We want the visual centre at `ground + radius`
                    // in world space; in wheel-local space that's
                    // `wheel_radius - distance` (the suspension extension
                    // below the mount, lifted by the wheel radius).
                    if let Some(visual_entity) = wheel.visual_entity {
                        if let Ok(mut visual_tf) = q_visual.get_mut(visual_entity) {
                            visual_tf.translation.y = (wheel.wheel_radius - distance) as f32;
                        }
                    }
                } else {
                    wheel.last_normal_force = 0.0;
                }
            } else {
                wheel.last_normal_force = 0.0;
            }
        }
    }
}

/// TEMP DIAGNOSTIC (forward+turn jitter): per-chassis per-tick wheel stats,
/// accumulated in `apply_wheel_drive` and logged by `debug_log_wheel_drive`.
/// Remove all three once the residual is localized.
#[derive(Clone, Copy)]
struct ChassisDriveDbg {
    n_min: f64,
    n_max: f64,
    long_max: f64,
    lat_max: f64,
    sat: u32,
    wheels: u32,
    fric_yaw_torque: f64,
}
impl ChassisDriveDbg {
    fn new() -> Self {
        Self {
            n_min: f64::MAX,
            n_max: 0.0,
            long_max: 0.0,
            lat_max: 0.0,
            sat: 0,
            wheels: 0,
            fric_yaw_torque: 0.0,
        }
    }
}
#[derive(Resource, Default)]
struct WheelDriveDebug(std::collections::HashMap<Entity, ChassisDriveDbg>);

/// TEMP DIAGNOSTIC: log the accumulated per-chassis wheel stats once per tick.
/// `nspread` = max−min normal force (weight transfer / suspension ripple);
/// `long`/`lat` = peak slip components; `sat` = wheels at the friction cone;
/// `fricYaw` = net friction yaw torque (does it reverse tick-to-tick?).
fn debug_log_wheel_drive(
    mut dbg: ResMut<WheelDriveDebug>,
    q: Query<(Entity, Option<&Name>, &AngularVelocity, &LinearVelocity), With<RoverVessel>>,
) {
    for (e, name, av, lv) in q.iter() {
        if let Some(d) = dbg.0.get(&e) {
            if av.0.length_squared() > 1e-6 || lv.0.length_squared() > 1e-4 {
                info!(
                    "WD rover='{}' yaw={:+.5} v={:.3} nspread={:.1} long={:.3} lat={:.3} sat={}/{} fricYaw={:+.4}",
                    name.map(|n| n.as_str()).unwrap_or("?"),
                    av.0.y,
                    lv.0.length(),
                    d.n_max - d.n_min,
                    d.long_max,
                    d.lat_max,
                    d.sat,
                    d.wheels,
                    d.fric_yaw_torque,
                );
            }
        }
    }
    dbg.0.clear();
}

/// System applying longitudinal drive torque and lateral friction.
///
/// **Theory**: Drive force is applied along the wheel's forward vector at the
/// world-space contact point. Both longitudinal (forward/back) and lateral
/// (side-to-side) friction are computed using a Coulomb friction model where
/// the maximum friction force is `mu * normal_force`. This prevents the rover
/// from sliding like it's on ice and limits drive force to what the tire can
/// actually grip.
fn apply_wheel_drive(
    q_wheels: Query<(
        &WheelRaycast,
        &Transform,
        &RayHits,
        &ChildOf,
    )>,
    q_ports: Query<&lunco_core::architecture::PhysicalPort>,
    mut q_chassis: Query<(Forces, &RigidBody, Option<&FlightSoftware>), With<RoverVessel>>,
    mut dbg: ResMut<WheelDriveDebug>,
) {
    for (wheel, wheel_tf, hits, parent) in q_wheels.iter() {
        let parent_entity = parent.parent();
        if let Ok((mut forces, body, fsw)) = q_chassis.get_mut(parent_entity) {
            // Skip forces if body is kinematic
            if matches!(body, RigidBody::Kinematic) { continue; }
            // Braking: the wheel-spin model locks the spin, but the chassis only
            // stops if the contact grips. We make friction saturate (full cone)
            // while braking so a locked wheel actually decelerates the rover.
            let braking = fsw.is_some_and(|f| f.brake_active);

            if let Ok(port) = q_ports.get(wheel.drive_port) {
                // Traction only exists when the ray is hitting the ground
                if hits.iter().next().is_some() {
                    let normal_force = wheel.last_normal_force;
                    if normal_force < 1.0 {
                        // Not enough contact to transmit meaningful force
                        continue;
                    }

                    // Reconstruct the wheel's world pose in the AVIAN physics frame
                    // from the chassis Position/Rotation + the wheel's LOCAL transform
                    // (exactly as `apply_wheel_suspension` does). Using `GlobalTransform`
                    // here mixed the big_space floating-origin/render frame into avian's
                    // cell-local frame: `forces.apply_force_at_point` and the lever arm
                    // `hub - forces.position()` then used a point offset by the whole
                    // origin-rebasing distance, producing spurious torque/slip once the
                    // rover drove away from the floating origin (masked near it).
                    // `wheel_tf.rotation` carries the steer angle (set in
                    // `apply_wheel_steering`); roll-spin lives on the child visual, so the
                    // drive direction stays correct.
                    let wheel_world_rot = forces.rotation().0 * wheel_tf.rotation.as_dquat();
                    let hub_pos_world =
                        forces.position().0 + forces.rotation().0 * wheel_tf.translation.as_dvec3();
                    let forward: DVec3 = wheel_world_rot * DVec3::NEG_Z;
                    let right: DVec3 = wheel_world_rot * DVec3::X;

                    // --- Drive force ---
                    // Physical port value is already scaled by the wire gain.
                    // Treated as a normalized throttle in [-1, 1]: positive drives
                    // forward, NEGATIVE drives in reverse (the differential mix on
                    // `DigitalPort` already carries the sign; clamping to 0 here was
                    // what blocked reverse).
                    let throttle = (port.value as f64).clamp(-1.0, 1.0);
                    let drive_force_mag = throttle * normal_force * DEFAULT_DRIVE_FORCE_PER_NORMAL;
                    let drive_force_vec = forward * drive_force_mag;
                    forces.apply_force_at_point(drive_force_vec, hub_pos_world);

                    // --- Friction (longitudinal + lateral) ---
                    // Coulomb friction cone: total friction force magnitude <= mu * N.
                    // `friction_mu` is the tyre/ground grip (USD-authored, per wheel).
                    let max_friction = wheel.friction_mu * normal_force;

                    let chassis_vel = forces.linear_velocity();
                    let chassis_ang_vel = forces.angular_velocity();
                    let hub_vel = chassis_vel + chassis_ang_vel.cross(hub_pos_world - forces.position().0);

                    // Longitudinal slip velocity (how fast the wheel is spinning vs rolling)
                    let long_vel = hub_vel.dot(forward);
                    // Lateral slip velocity (sideways sliding)
                    let lat_vel = hub_vel.dot(right);

                    // Combined slip speed and direction
                    // Friction opposes the slip *velocity vector*. Expressing it on
                    // the vector (not a normalized direction × magnitude behind a
                    // slip dead-band) keeps it a continuous damper through zero slip:
                    // `-k·slip` in the linear regime, saturating at the Coulomb cone
                    // `μ·N`. The old `if slip_speed > MIN_SLIP_SPEED` gate left
                    // sub-threshold motion UNDAMPED, so a resting/gently-turning
                    // chassis drifted free until it crossed the threshold, got snapped
                    // back, and drifted again — a stiction limit-cycle that showed up
                    // as a tick-period yaw chatter (the steering jitter). Smooth to
                    // zero removes it; at this mass `-k·slip` is well overdamped so it
                    // cannot overshoot.
                    let slip_vec = long_vel * forward + lat_vel * right;
                    let slip_speed = slip_vec.length();
                    let friction_force = if braking && slip_speed > 1e-6 {
                        // Braking: a locked wheel grips at the full Coulomb cone,
                        // opposing all sliding — this is what actually stops the rover.
                        -slip_vec * (max_friction / slip_speed)
                    } else if slip_speed * wheel.contact_grip_stiffness <= max_friction {
                        // Linear grip — `-k·slip`, → 0 continuously as slip → 0
                        // (no division, safe at exactly zero slip).
                        -slip_vec * wheel.contact_grip_stiffness
                    } else {
                        // Saturated at the cone; slip_speed > 0 here.
                        -slip_vec * (max_friction / slip_speed)
                    };
                    forces.apply_force_at_point(friction_force, hub_pos_world);

                    // TEMP DIAGNOSTIC (forward+turn jitter localization): accumulate
                    // per-chassis wheel stats this tick. Remove with its resource,
                    // logging system, and the `dbg` param.
                    let lever = hub_pos_world - forces.position().0;
                    let d = dbg.0.entry(parent_entity).or_insert_with(ChassisDriveDbg::new);
                    d.n_min = d.n_min.min(normal_force);
                    d.n_max = d.n_max.max(normal_force);
                    d.long_max = d.long_max.max(long_vel.abs());
                    d.lat_max = d.lat_max.max(lat_vel.abs());
                    if slip_speed * wheel.contact_grip_stiffness > max_friction {
                        d.sat += 1;
                    }
                    d.wheels += 1;
                    d.fric_yaw_torque += lever.cross(friction_force).y;
                }
            }
        }
    }
}

/// Updates steering angle based on physical port state.
///
/// The steering port value (normalized -1 to 1) is mapped to a yaw rotation
/// around the local Y axis. For front wheels on Ackermann rovers, this
/// produces the steer angle. For non-steering wheels, the port is
/// `Entity::PLACEHOLDER` and this system skips them.
fn apply_wheel_steering(
    mut q_wheels: Query<(&WheelRaycast, &mut Transform, &ChildOf)>,
    q_ports: Query<&lunco_core::architecture::PhysicalPort>,
    q_chassis: Query<&RigidBody, With<RoverVessel>>,
    mut q_visual: Query<&mut Transform, Without<WheelRaycast>>,
) {
    for (wheel, mut transform, parent) in q_wheels.iter_mut() {
        // Predict-own: this chain now runs on a client too (the `!Client` gate
        // was dropped so the owned rover steers locally). Unlike the suspension
        // and drive systems this one writes wheel rotation directly with no
        // physics guard — so gate it on the chassis the same way: skip wheels of
        // a `Kinematic` chassis (every replicated rover this peer does NOT own),
        // whose local steer ports are stale and would point the wheels wrong.
        if let Ok(body) = q_chassis.get(parent.parent()) {
            if matches!(body, RigidBody::Kinematic) {
                continue;
            }
        }
        if wheel.steer_port == Entity::PLACEHOLDER {
            continue;
        }
        if let Ok(port) = q_ports.get(wheel.steer_port) {
            // Port value is -1.0 to 1.0; map to +/- 0.5 rad (~30 degrees)
            let target_angle = (port.value as f32).clamp(-1.0, 1.0) * 0.5;
            // Steer rotation is around local Y (up) axis. The visual mesh
            // rotation (steer + roll spin) is composed in `update_wheel_spin`.
            transform.rotation = Quat::from_rotation_y(target_angle);
        }
    }
}

/// Control Logic: Differential (Skid) mixing.
/// 
/// **Math**: `Left = Forward + Steer`, `Right = Forward - Steer`. 
/// Creates a torque differential that rotates the chassis.
#[derive(Component, Debug, Clone, Reflect, Default)]
#[reflect(Component, Default)]
pub struct DifferentialDrive {
    /// Digital port identifier for left-side motors.
    pub left_port: String,
    /// Digital port identifier for right-side motors.
    pub right_port: String,
}

/// Control Logic: Ackermann Steering.
/// 
/// **Math**: `Drive = Forward`, `SteerAngle = Input * MaxAngle`. 
/// High-stability steering for vehicles with articulating front/rear axles.
#[derive(Component, Debug, Clone, Reflect, Default)]
#[reflect(Component, Default)]
pub struct AckermannSteer {
    /// Port name for drive motors (left).
    pub drive_left_port: String,
    /// Port name for drive motors (right).
    pub drive_right_port: String,
    /// Port name for the steering servo.
    pub steer_port: String,
    /// Maximum steering lock angle (radians).
    pub max_steer_angle: f32,
}

/// Suspension configuration for joint-based (non-raycast) chassis.
///
/// **Why**: Some vehicles use physical collision wheels for higher fidelity, 
/// but still require emulated spring-damper logic for PrismaticJoints.
#[derive(Component, Debug, Clone, Reflect)]
#[reflect(Component, Default)]
pub struct Suspension {
    /// target static length of the strut.
    pub rest_length: f64,
    /// Stiffness (N/m).
    pub spring_k: f64,
    /// Dampening (Ns/m).
    pub damping_c: f64,
    /// Direction of extension.
    pub local_axis: DVec3,
}

impl Default for Suspension {
    fn default() -> Self {
        Self {
            rest_length: 0.4,
            spring_k: 50000.0,
            damping_c: 2000.0,
            local_axis: DVec3::Y,
        }
    }
}

/// Solves linear suspension equations for entities linked by joints.
///
/// **Model**: Spring-damper using Hooke's law applied along the prismatic
/// joint's slider axis. Damping is bidirectional — it resists both compression
/// and extension to prevent oscillation. The force is applied as an equal and
/// opposite pair on the two connected bodies.
fn suspension_system(
    q_joints: Query<(&PrismaticJoint, &Suspension)>,
    mut q_bodies: Query<Forces>,
) {
    for (joint, susp) in q_joints.iter() {
        let e1 = joint.body1;
        let e2 = joint.body2;

        if let Ok([mut forces1, mut forces2]) = q_bodies.get_many_mut([e1, e2]) {
            let pos1 = forces1.position().0;
            let rot1 = forces1.rotation().0;
            let pos2 = forces2.position().0;
            let rot2 = forces2.rotation().0;

            let world_axis: DVec3 = rot1 * susp.local_axis;

            let anchor1_world: DVec3 = pos1 + rot1 * joint.local_anchor1().unwrap_or_default();
            let anchor2_world: DVec3 = pos2 + rot2 * joint.local_anchor2().unwrap_or_default();

            let diff_world: DVec3 = anchor2_world - anchor1_world;
            let current_length: f64 = -diff_world.dot(world_axis);
            let vel1 = forces1.velocity_at_point(anchor1_world);
            let vel2 = forces2.velocity_at_point(anchor2_world);
            let rel_vel: f64 = (vel2 - vel1).dot(world_axis);

            let compression: f64 = (susp.rest_length - current_length).max(0.0);
            let spring_force_mag: f64 = compression * susp.spring_k;

            // Damping opposes relative motion: positive when compressing (adds
            // force), negative when extending (reduces force). Clamp total to
            // zero minimum so we never pull bodies together.
            let damping_force_mag: f64 = rel_vel * susp.damping_c;
            let total_force_mag: f64 = (spring_force_mag + damping_force_mag).clamp(0.0, 100_000.0);

            if !total_force_mag.is_finite() { continue; }

            let force_vec: DVec3 = world_axis * total_force_mag;

            forces1.apply_force_at_point(force_vec, anchor1_world);
            forces2.apply_force_at_point(-force_vec, anchor2_world);
        }
    }
}

// ── Typed Commands ─────────────────────────────────────────────────────────────

/// Drive a rover forward/backward with optional steering.
///
/// `seq`/`tick` carry the client's per-vessel input sequence number + the
/// `SimTick` it was sampled at, for prediction reconciliation (the server echoes
/// the last-applied `seq` in snapshots; the client replays unacked inputs).
/// Field-level `default` keeps the HTTP API + older peers working when they omit
/// them (`DriveRover` can't derive `Default` — `Entity` has none).
#[Command]
pub struct DriveRover {
    #[authz_target]
    pub target: Entity,
    pub forward: f64,
    pub steer: f64,
    #[serde(default)]
    #[reflect(default)]
    pub seq: u32,
    #[serde(default)]
    #[reflect(default)]
    pub tick: u64,
}

/// Apply brakes to a rover. `seq`/`tick` as in [`DriveRover`] (paired input frame
/// shares the same `seq`).
#[Command]
pub struct BrakeRover {
    #[authz_target]
    pub target: Entity,
    pub intensity: f64,
    #[serde(default)]
    #[reflect(default)]
    pub seq: u32,
    #[serde(default)]
    #[reflect(default)]
    pub tick: u64,
}

// ── Command Observers ───────────────────────────────────────────────────────────

/// Observer for DriveRover commands.
#[on_command(DriveRover)]
fn on_drive_rover(
    cmd: DriveRover,
    mut q_rovers: Query<&mut FlightSoftware, With<RoverVessel>>,
    q_diff: Query<&DifferentialDrive>,
    q_ack: Query<&AckermannSteer>,
    mut q_digital_ports: Query<&mut DigitalPort>,
) {
    let Ok(fsw) = q_rovers.get_mut(cmd.target) else { return };

    if fsw.brake_active {
        for name in ["drive_left", "drive_right", "steering"] {
            if let Some(&port_id) = fsw.port_map.get(name) {
                if let Ok(mut p) = q_digital_ports.get_mut(port_id) { p.raw_value = 0; }
            }
        }
        return;
    }

    if let Ok(diff) = q_diff.get(cmd.target) {
        let left_mix = ((cmd.forward + cmd.steer) * 32767.0).clamp(-32767.0, 32767.0) as i16;
        let right_mix = ((cmd.forward - cmd.steer) * 32767.0).clamp(-32767.0, 32767.0) as i16;
        if let Some(&port_l) = fsw.port_map.get(&diff.left_port) {
            if let Ok(mut p) = q_digital_ports.get_mut(port_l) { p.raw_value = left_mix; }
        }
        if let Some(&port_r) = fsw.port_map.get(&diff.right_port) {
            if let Ok(mut p) = q_digital_ports.get_mut(port_r) { p.raw_value = right_mix; }
        }
    } else if let Ok(ack) = q_ack.get(cmd.target) {
        // Ackermann normally yaws the front wheels via a steering joint
        // — a `PhysicsRevoluteJoint` about Y between chassis and a
        // steering knuckle. We don't author those today, so the steer
        // port has no physical consumer on joint-based rovers. Until
        // those steering joints land, mix the steer command into the
        // left/right drive torques as a soft differential so the rover
        // can still turn under a `steer` command. The dedicated steer
        // port is still set for any consumer that implements true
        // Ackermann (raycast wheels render a visible steer angle from
        // it).
        // Skid-style mix at full magnitude until proper steering
        // knuckle joints (RevoluteJoint about Y between chassis and a
        // knuckle, with the wheel's X-axis hinge below the knuckle)
        // are authored. With the full mix the rover yaws under steer
        // input by spinning the L/R wheel groups in opposite
        // directions — visually identical to skid steer.
        let left_mix = ((cmd.forward + cmd.steer) * 32767.0).clamp(-32767.0, 32767.0) as i16;
        let right_mix = ((cmd.forward - cmd.steer) * 32767.0).clamp(-32767.0, 32767.0) as i16;
        let steer_val = (cmd.steer * 32767.0).clamp(-32767.0, 32767.0) as i16;
        if let Some(&port_l) = fsw.port_map.get(&ack.drive_left_port) {
            if let Ok(mut p) = q_digital_ports.get_mut(port_l) { p.raw_value = left_mix; }
        }
        if let Some(&port_r) = fsw.port_map.get(&ack.drive_right_port) {
            if let Ok(mut p) = q_digital_ports.get_mut(port_r) { p.raw_value = right_mix; }
        }
        if let Some(&port_s) = fsw.port_map.get(&ack.steer_port) {
            if let Ok(mut p) = q_digital_ports.get_mut(port_s) { p.raw_value = steer_val; }
        }
    }
}

/// Observer for BrakeRover commands.
#[on_command(BrakeRover)]
fn on_brake_rover(
    cmd: BrakeRover,
    mut q_rovers: Query<&mut FlightSoftware, With<RoverVessel>>,
    mut q_digital_ports: Query<&mut DigitalPort>,
) {
    let Ok(mut fsw) = q_rovers.get_mut(cmd.target) else { return };

    fsw.brake_active = cmd.intensity > 0.5;
    let port_val = if fsw.brake_active { 32767 } else { 0 };

    if let Some(&port_b) = fsw.port_map.get("brake") {
        if let Ok(mut p) = q_digital_ports.get_mut(port_b) { p.raw_value = port_val; }
    }
    if fsw.brake_active {
        for name in ["drive_left", "drive_right"] {
            if let Some(&port_id) = fsw.port_map.get(name) {
                if let Ok(mut port) = q_digital_ports.get_mut(port_id) { port.raw_value = 0; }
            }
        }
    }
}

// ── Registration ───────────────────────────────────────────────────────────────

register_commands!(
    on_drive_rover,
    on_brake_rover,
);


