//! Wire suggestions — UI-only recommendations, never auto-applied.
//!
//! Generated when a [`crate::SimComponent`] or [`crate::AvianSim`] is created.
//! The UI displays these for user review; clicking `[Accept]` creates a [`crate::SimConnection`].

use bevy::prelude::*;

/// A suggested wire connection for user review.
///
/// Generated by [`generate_suggestions`] when a new simulation model
/// is added to an entity. Suggestions are NEVER auto-applied — the user
/// must explicitly accept each one.
///
/// ## Display
///
/// The UI shows suggestions as:
/// ```text
/// → netForce could connect to avian:force_y  [Accept]
/// → volume could connect to self:collider    [Accept]
/// ```
#[derive(Event, Debug, Clone)]
pub struct WireSuggestion {
    /// Entity owning the start connector.
    pub start_element: Entity,
    /// Start connector name (output).
    pub start_connector: String,
    /// Entity owning the end connector.
    pub end_element: Entity,
    /// End connector name (input or special target).
    pub end_connector: String,
    /// Human-readable reason for the suggestion.
    pub reason: String,
    /// Confidence score for UI ordering (0.0-1.0).
    pub confidence: f64,
}

/// Known output variable names that suggest a force connection.
const KNOWN_FORCE_OUTPUTS: &[&str] = &["netForce", "force", "thrust", "buoyancy", "lift", "drag"];
/// Known output variable names that suggest a collider volume connection.
const KNOWN_VOLUME_OUTPUTS: &[&str] = &["volume", "vol"];
/// Known input variable names that suggest a gravity connection.
const KNOWN_GRAVITY_INPUTS: &[&str] = &["g", "gravity", "grav_accel"];

/// SimComponent **output** connector carrying an entity's local gravitational
/// acceleration magnitude (m/s²).
///
/// Cosim itself never produces this value — it would have to hardcode a
/// constant, and the master algorithm stays domain-agnostic. Instead a domain
/// system (lunco-environment's gravity bridge) writes the entity's real
/// [`LocalGravity`](https://docs.rs) magnitude into this output each tick, so
/// gravity flows through an ordinary output→input [`crate::SimConnection`] like
/// any other signal — correct on the Moon, Earth, or any body.
pub const GRAVITY_SOURCE_CONNECTOR: &str = "gravity_accel";

/// SimComponent **output** connector carrying the sun's azimuth (rad) at an
/// entity's location.
///
/// Same contract as [`GRAVITY_SOURCE_CONNECTOR`]: cosim stays domain-agnostic,
/// and a domain system (lunco-environment's solar bridge) writes the real value
/// from the scene sun each tick, so a sun-tracking model receives it through an
/// ordinary output→input [`crate::SimConnection`] — the doc's
/// `RadiationProvider → LocalRadiation → solar models` pipeline.
pub const SOLAR_AZIMUTH_CONNECTOR: &str = "sun_azimuth";
/// SimComponent **output** connector carrying the sun's elevation (rad) at an
/// entity's location. Companion to [`SOLAR_AZIMUTH_CONNECTOR`].
pub const SOLAR_ELEVATION_CONNECTOR: &str = "sun_elevation";

/// Prefix of the SimComponent **output** connectors `lunco-celestial`'s link bridge
/// writes on every link node, one set per authored peer `class`:
///
/// ```text
/// link_<class>_range_m        metres to the best peer of that class
/// link_<class>_connected      1.0 = geometry closes, 0.0 = severed
/// link_<class>_elevation_deg  that peer's elevation above the local horizon
/// ```
///
/// Same contract as [`SOLAR_AZIMUTH_CONNECTOR`]: cosim stays domain-agnostic and a domain
/// system writes the real value each solve, so an RF model (`CommsLink.mo`) receives it
/// through an ordinary output→input [`crate::SimConnection`].
///
/// WHY PER CLASS: `LinkState` already hands every peer to anything that can hold a list
/// (rhai, the API, the UI). Cosim is the one consumer that cannot — a Modelica port is a
/// fixed scalar — so N peers must reduce. `class` is the authored routing group that
/// exists for exactly this (three DSN complexes all author `class = "earth"`), which
/// keeps the choice of link with the AUTHOR:
///
/// ```usda
/// float inputs:link_range_m.connect = </…/Comms.outputs:link_relay_range_m>
/// ```
///
/// The model keeps generic inputs; the connection picks the link. Same `CommsLink.mo`
/// serves a relay uplink here and direct-to-Earth there, and a two-radio vehicle
/// instantiates it twice — no policy in the kernel, none in the model.
///
/// The kernel publishes GEOMETRY and only geometry: metres and a verdict, never a data
/// rate. Turning metres into bits/s is the authored channel model's job. And `connected`
/// is the geometry verdict ALONE — a peer can be in plain sight and still too far to
/// close the link budget; that verdict belongs to the model.
pub const LINK_CONNECTOR_PREFIX: &str = "link_";

/// Known input variable names that suggest a height connection.
const KNOWN_HEIGHT_INPUTS: &[&str] = &["height", "altitude", "h", "z"];
/// Known input variable names that suggest a velocity connection.
const KNOWN_VEL_INPUTS: &[&str] = &["velocity", "v", "speed", "vel"];

/// Generate wire suggestions for a newly created simulation model.
///
/// Called when a [`crate::SimComponent`] or [`crate::AvianSim`] is added to an entity.
/// Suggestions are based on connector name matching against known patterns.
///
/// ## Example
///
/// A balloon model with output `netForce` gets a suggestion:
/// `netForce → avian:force_y` with confidence 0.9.
pub fn generate_suggestions(
    entity: Entity,
    _model_name: &str,
    input_names: impl Iterator<Item = String>,
    output_names: impl Iterator<Item = String>,
    has_forces: bool,
    has_collider: bool,
) -> Vec<WireSuggestion> {
    let mut suggestions = Vec::new();

    // Output suggestions
    for output_name in output_names {
        if has_forces && KNOWN_FORCE_OUTPUTS.contains(&output_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: output_name.clone(),
                end_element: entity,
                end_connector: "force_y".into(),
                reason: format!("'{output_name}' is a known force output — connect to Avian force_y"),
                confidence: 0.9,
            });
        }
        if has_collider && KNOWN_VOLUME_OUTPUTS.contains(&output_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: output_name.clone(),
                end_element: entity,
                end_connector: "collider".into(),
                reason: format!("'{output_name}' suggests collider volume update"),
                confidence: 0.9,
            });
        }
    }

    // Input suggestions
    for input_name in input_names {
        if KNOWN_GRAVITY_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: GRAVITY_SOURCE_CONNECTOR.into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known gravity parameter — connect to the local gravity source"),
                confidence: 0.95,
            });
        }
        if KNOWN_HEIGHT_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: "height".into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known height input"),
                confidence: 0.9,
            });
        }
        if KNOWN_VEL_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: "velocity_y".into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known velocity input"),
                confidence: 0.85,
            });
        }
    }

    suggestions
}
