//! Wire suggestions — UI-only recommendations, never auto-applied.
//!
//! Generated when a [`SimComponent`] or [`AvianSim`] is created.
//! The UI displays these for user review; clicking `[Accept]` creates a [`SimWire`].

use bevy::prelude::*;

/// A suggested wire connection for user review.
///
/// Generated by [`generate_suggestions`] when a new simulation model
/// is added to an entity. Suggestions are NEVER auto-applied — the user
/// must explicitly accept each one.
///
/// ## Display
///
/// The UI shows suggestions as:
/// ```text
/// → netForce could connect to avian:force_y  [Accept]
/// → volume could connect to self:collider    [Accept]
/// ```
#[derive(Event, Debug, Clone)]
pub struct WireSuggestion {
    /// Entity owning the start connector.
    pub start_element: Entity,
    /// Start connector name (output).
    pub start_connector: String,
    /// Entity owning the end connector.
    pub end_element: Entity,
    /// End connector name (input or special target).
    pub end_connector: String,
    /// Human-readable reason for the suggestion.
    pub reason: String,
    /// Confidence score for UI ordering (0.0-1.0).
    pub confidence: f64,
}

/// Known output variable names that suggest a force connection.
const KNOWN_FORCE_OUTPUTS: &[&str] = &["netForce", "force", "thrust", "buoyancy", "lift", "drag"];
/// Known output variable names that suggest a collider volume connection.
const KNOWN_VOLUME_OUTPUTS: &[&str] = &["volume", "vol"];
/// Known input variable names that suggest a gravity resource connection.
const KNOWN_GRAVITY_INPUTS: &[&str] = &["g", "gravity", "grav_accel"];
/// Known input variable names that suggest a height connection.
const KNOWN_HEIGHT_INPUTS: &[&str] = &["height", "altitude", "h", "z"];
/// Known input variable names that suggest a velocity connection.
const KNOWN_VEL_INPUTS: &[&str] = &["velocity", "v", "speed", "vel"];

/// Generate wire suggestions for a newly created simulation model.
///
/// Called when a [`SimComponent`] or [`AvianSim`] is added to an entity.
/// Suggestions are based on connector name matching against known patterns.
///
/// ## Example
///
/// A balloon model with output `netForce` gets a suggestion:
/// `netForce → avian:force_y` with confidence 0.9.
pub fn generate_suggestions(
    entity: Entity,
    _model_name: &str,
    input_names: impl Iterator<Item = String>,
    output_names: impl Iterator<Item = String>,
    has_forces: bool,
    has_collider: bool,
) -> Vec<WireSuggestion> {
    let mut suggestions = Vec::new();

    // Output suggestions
    for output_name in output_names {
        if has_forces && KNOWN_FORCE_OUTPUTS.contains(&output_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: output_name.clone(),
                end_element: entity,
                end_connector: "force_y".into(),
                reason: format!("'{output_name}' is a known force output — connect to Avian force_y"),
                confidence: 0.9,
            });
        }
        if has_collider && KNOWN_VOLUME_OUTPUTS.contains(&output_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: output_name.clone(),
                end_element: entity,
                end_connector: "collider".into(),
                reason: format!("'{output_name}' suggests collider volume update"),
                confidence: 0.9,
            });
        }
    }

    // Input suggestions
    for input_name in input_names {
        if KNOWN_GRAVITY_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: "__gravity__".into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known gravity parameter"),
                confidence: 0.95,
            });
        }
        if KNOWN_HEIGHT_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: "height".into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known height input"),
                confidence: 0.9,
            });
        }
        if KNOWN_VEL_INPUTS.contains(&input_name.as_str()) {
            suggestions.push(WireSuggestion {
                start_element: entity,
                start_connector: "velocity_y".into(),
                end_element: entity,
                end_connector: input_name.clone(),
                reason: format!("'{input_name}' is a known velocity input"),
                confidence: 0.85,
            });
        }
    }

    suggestions
}
