[package]
name = "lunco-celestial-ephemeris"
version = "0.6.0-dev"
edition = "2021"
license.workspace = true

[dependencies]
lunco-assets-runtime = { path = "../lunco-assets-runtime" }
bevy = { workspace = true }
serde = { workspace = true }
lunco-celestial = { path = "../lunco-celestial", default-features = false }
lunco-assets-datasets = { path = "../lunco-assets-datasets" }
lunco-settings = { path = "../lunco-settings" }
celestial-ephemeris = "0.1.1-alpha.2"
celestial-time = "0.1.1-alpha.2"
celestial-core = "0.1.1-alpha.2"

[lints]
workspace = true
