[package]
name = "lunco-celestial-ephemeris"
version = "0.6.0-dev"
edition = "2024"
license.workspace = true

[dependencies]
bevy = { workspace = true }
lunco-celestial = { path = "../lunco-celestial", default-features = false }
celestial-ephemeris = { workspace = true }
celestial-time = { workspace = true }
celestial-core = { workspace = true }

[lints]
workspace = true
