//! High-performance Modelica integration for Bevy.
//!
//! This crate provides a bridge between Bevy's ECS and Modelica simulation models.
//! It features:
//! - A background worker thread that owns non-Send `SimulationSession` instances
//! - Command/response architecture with session ID fencing to prevent stale data
//! - Command squashing to handle rapid parameter changes without back-pressure
//! - DAE caching per entity for instant Reset and fast stepper rebuilds
//! - Real-time telemetry and plotting via egui
//!
//! ## Architecture
//!
//! The `ModelicaPlugin` spawns a background worker thread that owns all simulation
//! steppers and cached DAEs. The main Bevy thread sends `ModelicaCommand`s via a
//! crossbeam channel and receives `ModelicaResult`s back. Each entity with a
//! `ModelicaModel` component gets its own stepper instance, identified by a
//! `session_id` that increments on each recompile/reset to fence stale results.
//!
//! ## DAE Caching
//!
//! After a successful compilation, the `CompilationResult` (including the DAE) is
//! cached per entity. This enables:
//! - **Instant Reset**: Rebuilds the SimulationSession from the cached DAE without recompilation
//! - **Fast Step auto-init**: If the stepper was lost, rebuilds from cached DAE instead of
//!   recompiling from the file on disk
//! - **Parameter updates**: After UpdateParameters, the modified source is written to the
//!   temp file and the new DAE replaces the old cache entry
//!
//! ## Worker Panic Recovery
//!
//! The worker wraps all simulation logic in `catch_unwind`. If a numerical instability
//! (e.g., mass=0.0 in SpringMass) causes a solver panic, the error is caught and
//! reported as "Solver Error" in the logs rather than crashing the application.

use bevy::prelude::*;
use rumoca_compile::{Session, SessionConfig};
use crossbeam_channel::unbounded;
use std::thread;
use lunco_assets::msl_dir;

/// Typed identity for a Modelica class across the workbench.
///
/// Replaces the legacy string ID schemes (`msl_path:`, `bundled://…#`,
/// raw file paths, `mem://`) with a single `ClassRef { library, path }`
/// value that flows through opening, drill-in, tab dedup, projection
/// target lookup, and documentation lookup. See module docs for the
/// migration map.
pub mod class_ref;

/// Unified read-side metadata for Modelica classes — folds the
/// pre-baked palette index ([`visual_diagram::MSLComponentDef`]) and
/// the live per-document [`index::ClassEntry`] into one
/// [`class_metadata::ClassMetadata`] shape so docs view, badges,
/// and inspector title all read through one path.
pub mod class_metadata;

/// AST-based extraction functions for Modelica source code.
///
/// Walks the full Modelica AST (via `rumoca_phase_parse`) to extract model names,
/// parameters, inputs, and other symbols.
pub mod ast_extract;

/// Structural AST mutation helpers, one per `ModelicaOp` variant.
///
/// Each helper produces a **minimal text splice** against the original source
/// and mirrors the change into a cloned AST. Source is never regenerated by
/// re-emitting a class through rumoca's `to_modelica()` — that round-trip is
/// lossy (it drops comments and mis-renders any declaration carrying both a
/// `start` modifier and a binding), so a single canvas drag used to silently
/// rewrite every sibling declaration in the class.
///
/// See `ast_mut::edit` for the rule and
/// `tests/ast_mut_preserves_untouched_source.rs` for its enforcement.
pub mod ast_mut;

/// `ModelicaDocument` — the Document System representation of a `.mo` file.
///
/// Introduced dormant (no panels use it yet). See the module-level docstring
/// for migration order.
pub mod document;

/// Shared parse + I/O cache for Modelica classes. Drill-in, AddComponent
/// preload, and compile dep-walk all funnel through here so every class file is
/// read once, parsed once, and shared as an `Arc` across tabs and compile jobs.
///
/// The load is **synchronous** (`peek_or_load_msl_class_blocking`), under a
/// two-phase lock: probe → parse *outside* the lock → install. That is why
/// [`MslLookupMode::Cached`] exists — off-thread callers must never block on a
/// cold parse, so they take the peek-only path and miss rather than stall.
pub mod class_cache;
pub mod library_fs;

/// Subset Modelica pretty-printer — emits source snippets for *new* AST
/// nodes (component declarations, connect equations, placement / line
/// annotations). Used by AST-level document ops that splice new text at
/// a span in the existing source. Not a full round-trip printer —
/// existing nodes keep their original source text.
pub mod pretty;

/// Modelica-to-diagram graph builder — converts AST into DiagramGraph.
pub mod diagram;

/// Typed extractors for graphical annotations (Placement, Icon, Diagram,
/// and the common `graphics={...}` primitives). Walks the raw
/// `Vec<Expression>` that rumoca preserves on each class/component and
/// produces structs ready for the canvas renderer.
pub mod annotations;

/// One invalidation signal for every memo derived from Modelica source — the
/// engine's merged icons and the paint side's decoded bitmap textures. Before it,
/// three memos were invalidated by three unrelated mechanisms and the bitmap cache
/// by none, so a missing asset was remembered as missing for the life of the
/// process.
pub mod icon_memo;

/// egui painter for the typed graphics produced by [`annotations`].
/// Renders `Rectangle`, `Line`, `Polygon`, and `Text` directly into a
/// destination screen rect, mapping Modelica diagram coordinates
/// (+Y up) to egui screen coordinates (+Y down).
// `icon_paint` lives under `ui/` — it's a UI/rendering concern, not
// a model-semantics one. Re-exported here so the previous flat path
// (`lunco_modelica::icon_paint::*`) keeps compiling for any external
// consumer that hardcoded it.
#[cfg(feature = "ui")]
pub use ui::icon_paint;

/// Single 2×3 affine transform per node from Modelica icon-local
/// coords to canvas world coords. Replaces the scattered
/// position/extent_size/rotation/mirror fields with one matrix that
/// every consumer (port placement, edge stub direction, icon body
/// painting, AABB) shares.
pub mod icon_transform;

/// Visual diagram editor — drag-and-drop component composition.
pub mod visual_diagram;

// ── Egui-free core modules lifted out of the (egui-gated) `ui` module so the
//    headless / server build (`--no-default-features`) compiles. The egui
//    rendering for these lives under `ui::panels::*`. ────────────────────────
/// Workbench-side document registry + shared UI-agnostic state (was `ui::state`).
pub mod state;
/// Modelica tab registry data types (was `ui::panels::model_view::types`).
pub mod model_tabs_types;
/// `ModelTabs` registry (was `ui::panels::model_view::tabs`).
pub mod model_tabs;
/// Core data for API-driven canvas focus/connection pulses (UI drains them).
pub mod canvas_feedback;
/// Documentation annotation extractor (was `ui::panels::model_view::parsing`).
pub mod doc_extract;
/// Default-simulation-class resolution + run-target overrides
/// (was `ui::panels::model_view::context::default_simulation_class` & friends).
pub mod sim_default;
/// Package-tree backend: egui-free data + scanning logic for the library /
/// package browser (was `ui::panels::package_browser::{types,scanner,cache,library_tree}`).
pub mod package_tree;
/// Egui-free Modelica document ops application
/// (was `ui::panels::canvas_diagram::ops::apply_one_op_as` & helpers).
pub mod doc_ops;

/// Per-document UI projection — what panels read instead of the AST.
/// Skeleton; population happens in the upcoming AST-canonical refactor.
/// See `docs/architecture/REFACTOR_PLAN.md`.
pub mod index;

/// Pure simulation-target & run-configuration resolution (which class to
/// run, what bounds to run it with). No `World`/UI deps — the `ui/` layer
/// gathers inputs and calls down. See [`sim_target`].
pub mod sim_target;

/// Core (UI-free) Modelica command helpers — `SetModelInput` application + sim-
/// bounds resolution — shared by the egui workbench and the headless API server.
pub mod model_commands;

/// Per-Twin Modelica domain engine: long-lived `rumoca_compile::Session`
/// + per-doc URI mapping. Provides cross-file inheritance-merged queries.
pub mod engine;
pub mod engine_resource;

/// Modelica adapter to the canonical Twin journal in
/// `lunco-twin-journal`. Records each applied [`crate::document::ModelicaOp`] as a
/// summary entry alongside its inverse. See module docs for the
/// "summary, not full Serialize" rationale.
pub mod journal;
/// Experiment-*definition* journaling (`DomainKind::Experiment`) — records
/// create/rename/bounds/params/delete into the canonical twin journal so
/// experiment setups sync + persist. Run results ride the content plane; run
/// status rides presence.
pub mod experiment_journal;

/// Minimal byte-range diff helper. Used by the code-editor commit path
/// to convert a debounced full-buffer snapshot into a single
/// `ModelicaOp::EditText` splice — finer undo granularity and
/// CRDT-friendly text edits.
pub mod text_diff;

/// Pre-warmer: walks each opened doc's AST collecting cross-package
/// type references, then primes the engine's icon cache via a single
/// off-thread task. Drill-in projection sees a populated cache.
pub mod icon_warmer;
pub mod lock_ext;
pub mod source_roots;

/// Simple wrapper around rumoca-compile for compiling Modelica models.
///
/// MSL is preloaded into the session at construction time via
/// [`rumoca_compile::compile::Session::load_source_root_tolerant`].
/// After preload, compiling any MSL-based user model is a plain
/// strict-reachable-DAE call against a session that already has
/// every MSL class visible to rumoca's §5 scope walker.
///
/// Why preload instead of demand-load? Demand-load requires
/// rumoca to emit fully-qualified references in its unresolved-ref
/// diagnostics so an external source provider can act on them.
/// Upstream rumoca currently emits raw short forms (`SI.Time`,
/// `Continuous.Filter`, `Rotational.Interfaces.PartialTwoFlanges`)
/// without scope qualification — which means an external resolver
/// has no way to disambiguate. Preload sidesteps the issue: once
/// every MSL class is in the session, the scope walker never has
/// to ask outside.
///
/// Cost: first session construction blocks while the parsed-artifact
/// cache (bincode under `RUMOCA_CACHE_DIR`) is hit. With a warm
/// cache, MSL loads in ~2–5 s. Cold cache (first run after a rumoca
/// version bump) is proportional to parser throughput; `msl_indexer`
/// can pre-warm offline.
/// Cheap, side-effect-free check for whether a library set is installable
/// on this target — used to gate the demand-driven MSL install so we never
/// run a redundant strict pass / install attempt when there's nothing to
/// install. Does NOT decode the bundle (that's the expensive part): it only
/// looks for an already-decoded process-wide slot, a native MSL filesystem
/// root, or a web in-memory source.
fn msl_is_available() -> bool {
    msl_remote::global_parsed_msl().is_some()
        || lunco_assets::msl::primary_filesystem_root().is_some()
        || lunco_assets::msl::has_in_memory_source()
        // On-disk tree even if not registered as a global source. The app
        // registers MSL at startup (so `primary_filesystem_root` is set), but
        // headless contexts (unit tests, the indexer, a fresh embedder) only
        // have the files on disk — demand-driven load must still find them.
        || lunco_assets::msl_source_root_path().is_some()
}

pub struct ModelicaCompiler {
    session: Session,
    /// Whether the library set (MSL + companions + discovered extra libs)
    /// has been installed into this session yet. Layer-A demand-driven gate:
    /// MSL is installed lazily by [`Self::compile_loaded`] on the first
    /// compile whose failure rumoca attributes to an unresolved reference
    /// (`ER002`) — never at construction. A library-free model never sets
    /// this and never pays the MSL cost. Latches `true` after one install
    /// so subsequent compiles skip the gate entirely.
    msl_installed: bool,
    /// Whether the shipped `LunCo` Modelica library (`assets/models/LunCo`, a
    /// standard structured package) has been seated into this session. Same
    /// demand-driven gate as [`Self::msl_installed`], but the library is tiny and
    /// always embedded, so the install is a handful of in-memory documents rather
    /// than MSL's 316 MB bundle. Seated on the first compile whose failure rumoca
    /// attributes to an unresolved reference — e.g. a rover's `rucheyok_electrical.mo`
    /// referencing `LunCo.Electrical.Battery`.
    lunco_installed: bool,
    /// URIs of the user documents currently seated as overlays in this
    /// reused session (NOT the MSL/library source roots). Every compile is
    /// HERMETIC with respect to prior compiles: before seating its own
    /// document set, a compile evicts any previously-seated user doc that is
    /// not part of *this* compile. Without this, a prior compile's primary
    /// overlay stays resident, and compiling a SECOND document that defines
    /// the same package (e.g. the same model opened in two tabs / restored +
    /// shared) leaves the package registered under two URIs → rumoca's merge
    /// pass fails with `Duplicate class '…' found in '…' with non-identical
    /// definition`. The per-doc `session_uri` keying alone can't prevent this
    /// because the two docs legitimately have different URIs; the session
    /// itself must hold only the active compile's user docs.
    seated_user_uris: std::collections::HashSet<String>,
}

impl ModelicaCompiler {
    /// Construct a compiler and preload MSL.
    ///
    /// MSL discovery order:
    ///
    /// 1. The process-wide source from [`lunco_assets::msl::global_msl_source`]
    ///    if it's been installed. This is how the wasm runtime feeds the
    ///    fetched-from-server MSL bundle in.
    /// 2. Fall back to [`lunco_assets::msl_source_root_path`] (filesystem).
    ///
    /// If both are absent — typical for the first wasm tick before the
    /// MSL bundle has finished downloading — the session is left empty
    /// and the next compile will surface `unresolved type reference`
    /// diagnostics until MSL lands. Callers that want to gate compiles
    /// on MSL readiness should consult `MslLoadState`.
    pub fn new() -> Self {
        // Layer A: build an EMPTY session — MSL is no longer installed
        // eagerly here. A library-free model (Balloon, standalone) then
        // compiles against the empty session in a fraction of the time and
        // never pays the ~1.5s MSL decode+install nor the cost of resolving
        // against 2670 resident classes. MSL is installed on demand by
        // `compile_loaded` only when rumoca reports an unresolved reference
        // (`ER002`) that a library could satisfy — the decision comes from
        // rumoca's own structured diagnostics, not a source-text guess.
        let mut compiler = Self {
            session: Session::new(SessionConfig::default()),
            msl_installed: false,
            lunco_installed: false,
            seated_user_uris: std::collections::HashSet::new(),
        };
        // Escape hatch: `LUNCO_MODELICA_PRELOAD_MSL=1` forces the old eager
        // behaviour, e.g. to pre-pay the install before a latency-sensitive
        // interactive run. Default off — the demand-driven path covers it.
        let eager = std::env::var("LUNCO_MODELICA_PRELOAD_MSL")
            .map(|v| v != "0" && !v.is_empty())
            .unwrap_or(false);
        if eager {
            compiler.ensure_msl_installed();
        }
        compiler
    }

    /// Install the library set (MSL + companions + discovered extra libs)
    /// into this session, once. Returns `true` if classes are now resident
    /// (just installed, or already were). Idempotent and cheap on repeat.
    ///
    /// This is the demand-driven install hook. It reuses the same
    /// [`Self::preload_from_global`] machinery the old eager path used
    /// (process-wide decoded bundle → on-disk `parsed-msl.bin` → cold
    /// parse), so there is exactly one install code path. Callers that
    /// *know* they need the full library up front (the `msl_indexer --warm`
    /// pass) call this explicitly; `compile_loaded` calls it lazily on an
    /// unresolved-reference failure.
    pub fn ensure_msl_installed(&mut self) -> bool {
        if self.msl_installed {
            return true;
        }
        let t = web_time::Instant::now();
        if Self::preload_from_global(&mut self.session, t) {
            self.msl_installed = true;
        }
        self.msl_installed
    }

    /// Seat the shipped `LunCo` Modelica library into this session, once.
    ///
    /// The library is `assets/models/LunCo` — a standard structured package
    /// (`package.mo` + `package.order` + members), embedded at compile time by
    /// `lunco_assets::models` so it is present on every target including wasm. This
    /// loads it via [`Session`]'s in-memory source-root path, the same call bundled
    /// examples use; rumoca then resolves `import LunCo.Electrical` the standard way,
    /// from the packages' `within` declarations. Idempotent; cheap (a few small docs).
    pub fn ensure_lunco_installed(&mut self) -> bool {
        if self.lunco_installed {
            return true;
        }
        let files = lunco_assets::models::package_files("LunCo");
        if files.is_empty() {
            return false;
        }
        let _ = self.load_source_root_in_memory("LunCo", "LunCo", files);
        self.lunco_installed = true;
        true
    }

    /// If a process-wide MSL has been installed, preload it into the
    /// session. Returns `true` when handled (caller skips the disk
    /// fallback).
    ///
    /// Two web-side fast paths, in priority order:
    ///
    /// 1. **Pre-parsed bundle** ([`msl_remote::global_parsed_msl`]).
    ///    The chunked parse driver finished running, so we already have
    ///    `Vec<(uri, StoredDefinition)>` in hand — install via
    ///    `Session::replace_parsed_source_set` (no parsing). This is
    ///    the steady-state path on web.
    /// 2. **Source-only bundle** (`MslAssetSource::InMemory`). Bytes
    ///    are decompressed but the chunked parser hasn't finished yet.
    ///    Falling through to `load_source_root_in_memory` here would
    ///    block the main thread for ~60–120 s, so we skip preload and
    ///    let the caller see an empty session — the auto-retrigger on
    ///    parse-complete will rebuild the compiler properly.
    fn preload_from_global(session: &mut Session, t_total: web_time::Instant) -> bool {
        // 1. Slot hit, shared by native and wasm: the pre-parsed bundle is
        //    already in memory (wasm chunked-decoder output, or a prior
        //    native load that populated the process-wide slot). Cheap
        //    install, no disk. Kept slot-only on purpose so a non-MSL
        //    caller (sandbox/Balloon, `SkipMslAutoLoad`) never eagerly
        //    reads the on-disk bundle here — the native disk read lives in
        //    branch 3, behind the `Filesystem`-source gate.
        if let Some(parsed) = msl_remote::global_parsed_msl() {
            let docs = (**parsed).clone();
            let pair_count = docs.len();
            let inserted = session.replace_parsed_source_set(
                "msl",
                rumoca_compile::compile::SourceRootKind::DurableExternal,
                docs,
                None,
            );
            log::info!(
                "[ModelicaCompiler] installed pre-parsed MSL in {:.2}s: \
                 {} inserted (of {} docs)",
                t_total.elapsed().as_secs_f64(),
                inserted,
                pair_count,
            );
            return true;
        }
        if lunco_assets::msl::has_in_memory_source() {
            // wasm: the source bytes are resident but the chunked parser
            // hasn't produced `StoredDefinition`s yet. Report `false`
            // (nothing installed) so `ensure_msl_installed` does NOT latch —
            // a later compile retries once the chunked decode lands and
            // `global_parsed_msl()` fills (branch 1 above).
            log::info!(
                "[ModelicaCompiler] MSL bundle present but parse not yet complete — \
                 session stays empty; install retried when parse finishes"
            );
            return false;
        }
        if lunco_assets::msl::primary_filesystem_root().is_some()
            || lunco_assets::msl_source_root_path().is_some()
        {
            // Native: an MSL tree is present (registered as a global source,
            // OR just materialised on disk — headless tests/indexer/embedders
            // don't register one). The install paths below read the on-disk
            // bundle / source tree via `msl_dir()` directly, so disk presence
            // alone is enough. Try the pre-parsed on-disk bundle first via the
            // shared, memoized
            // `install_parsed_msl` path — it streams `parsed-msl.bin` and
            // caches it process-wide, so the next `ModelicaCompiler` hits
            // branch 1 above with no disk read. This is the exact same
            // install `load_source_root` uses: one code path, native + wasm.
            if let Some((total, inserted)) = Self::install_parsed_msl(session, "msl") {
                log::info!(
                    "[ModelicaCompiler] loaded pre-parsed MSL bundle in {:.2}s: \
                     {} inserted (of {} docs)",
                    t_total.elapsed().as_secs_f64(),
                    inserted,
                    total,
                );
                return true;
            }

            // No usable bundle (missing, or rumoca-version-stale and failed
            // to decode). Cold path: build the bundle the SAME way
            // `msl_indexer` does — `indexer::parse_native_msl_bundle` walks
            // every native root (MSL tree + companions + discovered extra
            // libs) and parses ONE FILE AT A TIME.
            //
            // We deliberately do NOT use rumoca's
            // `parse_source_root_with_cache_in`: it fires a single
            // all-files rayon batch, which spikes memory (up to `num_cpus`
            // concurrent ASTs + a full-tree blake3 hash sweep) and bursts
            // concurrent artifact-cache writes. Fine standalone, but here it
            // runs on the worker thread *alongside the Bevy render loop*, so
            // on weak (8 GB) machines the peak swaps and stalls the whole
            // desktop. Per-file keeps the peak flat — `msl_indexer` has
            // always parsed this way and finishes in minutes where the batch
            // path took tens of minutes. DRY: one MSL source→bundle parser
            // shared by the CLI and the workbench.
            #[cfg(not(target_arch = "wasm32"))]
            {
                let docs = crate::indexer::parse_native_msl_bundle();
                if docs.is_empty() {
                    log::warn!(
                        "[ModelicaCompiler] no MSL source files found under native \
                         roots; session starts empty"
                    );
                    return false;
                }
                let parsed_count = docs.len();
                // Write the bundle (zstd-compressed) BEFORE moving the docs
                // into the session so we don't clone ~165 MB of defs, and so
                // the next launch hits the fast path above (~1s).
                let bundle_path = lunco_assets::msl_dir().join("parsed-msl.bin");
                if let Some(parent) = bundle_path.parent() {
                    let _ = std::fs::create_dir_all(parent);
                }
                match msl_remote::write_parsed_bundle(&bundle_path, &docs) {
                    Ok(()) => log::info!(
                        "[ModelicaCompiler] wrote compressed MSL bundle ({} docs) to `{}` — next launch will be ~1s",
                        docs.len(),
                        bundle_path.display()
                    ),
                    Err(e) => log::warn!(
                        "[ModelicaCompiler] failed to write MSL bundle to `{}`: {e}",
                        bundle_path.display()
                    ),
                }
                let inserted = session.replace_parsed_source_set(
                    "msl",
                    rumoca_compile::compile::SourceRootKind::DurableExternal,
                    docs,
                    None,
                );
                log::info!(
                    "[ModelicaCompiler] preloaded MSL (cold, per-file) in {:.2}s: \
                     {} parsed / {} inserted",
                    t_total.elapsed().as_secs_f64(),
                    parsed_count,
                    inserted,
                );
                return true;
            }
            #[cfg(target_arch = "wasm32")]
            return false;
        }
        false
    }

    /// Install the process-wide pre-parsed MSL bundle into `session`
    /// under source-set `id`, if a bundle is available.
    ///
    /// **Single shared path for native and wasm.** The bundle is acquired
    /// through [`msl_remote::parsed_msl_bundle`], the one memoized
    /// accessor: on native it streams `parsed-msl.bin` off disk on the
    /// first call and caches it process-wide (so a second
    /// `ModelicaCompiler`, or a later [`Self::load_source_root`], reuses
    /// it with no extra read/decode); on wasm it returns the chunked
    /// decoder's slot. Both [`Self::preload_from_global`] and
    /// [`Self::load_source_root`] go through here, so a change to how MSL
    /// is sourced or installed lands on both targets at once.
    ///
    /// Returns `Some((total_docs, inserted))`, or `None` when no bundle is
    /// ready yet (wasm before the chunked parse finishes, or native before
    /// the indexer has written `parsed-msl.bin`).
    fn install_parsed_msl(session: &mut Session, id: &str) -> Option<(usize, usize)> {
        // The three real costs here are: decode `parsed-msl.bin`, deep-clone
        // the (~165MB) AST set off the Arc, and insert+invalidate in the
        // session. The clone dominates — see CQ-213 for eliminating it.
        let parsed = msl_remote::parsed_msl_bundle()?;
        let docs = (**parsed).clone();
        let total = docs.len();
        let inserted = session.replace_parsed_source_set(
            id,
            rumoca_compile::compile::SourceRootKind::DurableExternal,
            docs,
            None,
        );
        log::debug!("[install_parsed_msl] {total} docs, {inserted} inserted");
        Some((total, inserted))
    }

    /// Compile Modelica source string and return DAE result.
    ///
    /// The user source is fed as a workspace document on top of the
    /// already-preloaded MSL. Rumoca's strict-reachable DAE walker
    /// sees the user's model plus the entire MSL class tree, so
    /// short-form refs like `SI.Time`, `Continuous.Filter`, etc.
    /// resolve through normal MLS §5 scope lookup.
    ///
    /// `filename` is used as the document URI for error reporting.
    pub fn compile_str(
        &mut self,
        model_name: &str,
        source: &str,
        filename: &str,
    ) -> Result<Box<rumoca_compile::compile::DaeCompilationResult>, String> {
        let mut keep = std::collections::HashSet::new();
        keep.insert(filename.to_string());
        self.evict_user_docs_except(&keep);
        self.seat_user_source(filename, source);
        self.seated_user_uris = keep;
        self.compile_loaded(model_name)
    }

    /// Seat one user source into the session — **the single chokepoint where
    /// user model text enters rumoca**, and therefore the one place the
    /// bound-`input` workaround is applied.
    ///
    /// rumoca demotes a bound `input Real g = 9.81` to an algebraic, so it never
    /// reaches `input_names()` and `set_input("g", …)` fails
    /// (`docs/architecture/29-rumoca-workarounds.md` §2). Stripping here rather
    /// than at each caller means no compile path can forget it — `modelica_tester`
    /// silently did, and every future entry point would have been one `git grep`
    /// away from the same bug.
    ///
    /// Safe to apply to already-stripped source: [`strip_input_defaults`] blanks
    /// the binding bytes in place, so a second pass finds nothing to strip and is
    /// a no-op. Callers that need the defaults back (the worker, to re-seed them
    /// via `set_input`) still call it themselves — they get the same answer.
    ///
    /// The blanking is LENGTH-PRESERVING, so byte offsets into the raw source the
    /// caller still holds (diagnostic spans → editor click-to-source) keep
    /// pointing at the same characters.
    fn seat_user_source(&mut self, filename: &str, source: &str) {
        let (stripped, _defaults) = crate::ast_extract::strip_input_defaults(source);
        self.session.update_document(filename, &stripped);
    }

    /// Remove every previously-seated user-document overlay whose URI is not
    /// in `keep`, so the reused session holds ONLY the active compile's user
    /// docs (plus the immutable MSL/library source roots). This is what makes
    /// each compile hermetic against prior compiles — see
    /// [`Self::seated_user_uris`]. MSL roots are installed via
    /// `replace_parsed_source_set` (not tracked here), so they're untouched.
    fn evict_user_docs_except(&mut self, keep: &std::collections::HashSet<String>) {
        let stale: Vec<String> = self
            .seated_user_uris
            .iter()
            .filter(|uri| !keep.contains(*uri))
            .cloned()
            .collect();
        for uri in stale {
            self.session.remove_document(&uri);
            self.seated_user_uris.remove(&uri);
        }
    }

    /// Recompute **structured, located** diagnostics for a model that
    /// just failed [`Self::compile_str`].
    ///
    /// Where `compile_str`'s `Err(String)` is a flat human summary,
    /// this returns one [`Diagnostic`](lunco_doc::Diagnostic) per
    /// rumoca failure — each prefixed with the diagnostic code
    /// (e.g. `[ED008]`) and, when the failure's primary span points
    /// into the user's `model.mo`, carrying a 1-based (line, column)
    /// so the Diagnostics panel can make the row click-to-source
    /// (the same treatment parse + lint findings already get).
    ///
    /// Runs rumoca's report-returning strict compile
    /// (`compile_model_strict_reachable_uncached_with_recovery`),
    /// which reuses the session's already-resolved AST/source — so
    /// this is a cheap second pass, taken only on the error path.
    /// `user_uri` is the document URI the caller passed to
    /// `compile_str` (`"model.mo"` for the workbench); only spans in
    /// that file are made clickable.
    pub fn compile_diagnostics(
        &mut self,
        model_name: &str,
        user_uri: &str,
    ) -> Vec<lunco_doc::Diagnostic> {
        let report = self
            .session
            .compile_model_strict_reachable_uncached_with_recovery(model_name);
        diagnostics_from_strict_report(&report, user_uri)
    }

    /// Like `compile_str`, but seats additional `(filename, source)`
    /// pairs into the rumoca session before compiling so the resolver
    /// can satisfy cross-doc class references (e.g. a fresh untitled
    /// `RocketStage` referencing `AnnotatedRocketStage.Tank` from a
    /// sibling untitled doc that holds the package). Each extra is
    /// loaded via the same `update_document` path; rumoca dedups by
    /// filename so re-loading the same file is harmless.
    ///
    /// The active compile's user docs (primary + extras) become the session's
    /// ENTIRE user-overlay set: any previously-seated user doc that isn't part
    /// of this compile is evicted first (see [`Self::seated_user_uris`] /
    /// [`Self::evict_user_docs_except`]). This keeps the reused session
    /// hermetic — a prior compile of the same package under a different URI
    /// (e.g. the same model open in two tabs) can't linger and trip rumoca's
    /// `Duplicate class '…' found in '…' with non-identical definition`. The
    /// seated docs are left resident on return (the error-path
    /// `compile_diagnostics` re-reads them); they're pruned by the NEXT
    /// compile, not removed here.
    pub fn compile_str_multi(
        &mut self,
        model_name: &str,
        source: &str,
        filename: &str,
        extras: &[(String, String)],
    ) -> Result<Box<rumoca_compile::compile::DaeCompilationResult>, String> {
        let mut keep = std::collections::HashSet::new();
        keep.insert(filename.to_string());
        for (extra_filename, _) in extras {
            if extra_filename != filename {
                keep.insert(extra_filename.clone());
            }
        }
        self.evict_user_docs_except(&keep);
        for (extra_filename, extra_source) in extras {
            if extra_filename == filename {
                continue;
            }
            self.seat_user_source(extra_filename, extra_source);
        }
        self.seat_user_source(filename, source);
        self.seated_user_uris = keep;
        self.compile_loaded(model_name)
    }

    /// Compile an MSL class that is already loaded into the session
    /// (no `update_document` call). Used by the `msl_indexer --warm`
    /// pass to populate rumoca's semantic-summary cache for common
    /// examples — the workbench's first compile of those classes is
    /// then a cache hit instead of paying the full multi-minute walk.
    pub fn compile_msl_class(
        &mut self,
        qualified: &str,
    ) -> Result<Box<rumoca_compile::compile::DaeCompilationResult>, String> {
        self.compile_loaded(qualified)
    }

    /// Inner helper: heartbeat + session.compile + final timing log.
    /// Both [`Self::compile_str`] (user-edited source) and
    /// [`Self::compile_msl_class`] (already-loaded MSL class) flow
    /// through here so the heartbeat behaviour is identical.
    fn compile_loaded(
        &mut self,
        model_name: &str,
    ) -> Result<Box<rumoca_compile::compile::DaeCompilationResult>, String> {
        let t_total = web_time::Instant::now();

        // Heartbeat: rumoca's compile pipeline is opaque from outside
        // and can take minutes on cold caches with MSL-heavy models
        // (parol Debug::fmt overhead — see ../rumoca/docs/design-notes/
        // perf-parol-trace-overhead.md). Without a periodic log line,
        // the user sees nothing for the entire duration and reasonably
        // assumes the worker hung. Spawn a tiny thread that emits an
        // INFO log every 5s while the synchronous compile is in
        // flight; signal it to stop on return.
        //
        // Wasm note: `std::thread::spawn` panics on wasm32-unknown-unknown
        // (single-threaded target). The compile already runs on the main
        // task there via the inline worker, so the user sees the freeze
        // anyway — heartbeat would just be cosmetic. Skip it.
        use std::sync::atomic::{AtomicBool, Ordering};
        let still_compiling = std::sync::Arc::new(AtomicBool::new(true));
        #[cfg(not(target_arch = "wasm32"))]
        {
            let stopper = std::sync::Arc::clone(&still_compiling);
            let model_for_thread = model_name.to_string();
            // Spawn detached — we deliberately do NOT join after compile
            // returns. The heartbeat sleeps in 5-second chunks; joining
            // would block the worker for up to a full tick (5 s) on EVERY
            // compile, even fast cache-hit ones. The workbench's
            // is_compiling flag would then stay set for that whole window,
            // and the Step dispatcher would idle visibly. Letting the
            // JoinHandle drop detaches the thread; it self-exits within
            // 5 s of `stopper=false` with at most one stray "still
            // compiling +N s" log line if the timing aligns badly.
            let _ = std::thread::spawn(move || {
                let started = web_time::Instant::now();
                let tick = std::time::Duration::from_secs(5);
                loop {
                    std::thread::sleep(tick);
                    if !stopper.load(Ordering::Relaxed) {
                        return;
                    }
                    log::info!(
                        "[ModelicaCompiler] still compiling `{}` (+{:.0}s)",
                        model_for_thread,
                        started.elapsed().as_secs_f64()
                    );
                }
            });
        }

        let mut result = self
            .session
            .compile_model_dae_strict_reachable_uncached_with_recovery(model_name);

        // Demand-driven libraries. If the compile failed, ask rumoca *why*: only an
        // unresolved-reference code (`ER002`/`ER003`) — a class a library could supply
        // — triggers an install. A library-free model (Balloon) succeeds first pass and
        // never reaches here; a genuinely broken model (syntax error, typo) fails with a
        // different code and is returned as-is, paying no install.
        //
        // CHEAPEST FIRST, and each gated independently so a model needing only one does
        // not pay the other. `LunCo` is a handful of embedded docs, so any unresolved
        // reference earns it. MSL is a 316 MB bundle, so it is reached for ONLY if the
        // target STILL has unresolved refs after `LunCo` — otherwise every EPS model
        // (which references `LunCo` but not MSL) would drag MSL in for nothing.
        if result.is_err() && !self.lunco_installed && self.target_has_unresolved_refs(model_name) {
            if self.ensure_lunco_installed() {
                log::info!("[ModelicaCompiler] `{model_name}` had unresolved refs — installed LunCo, retrying");
                result = self
                    .session
                    .compile_model_dae_strict_reachable_uncached_with_recovery(model_name);
            }
        }
        if result.is_err()
            && !self.msl_installed
            && msl_is_available()
            && self.target_has_unresolved_refs(model_name)
            && self.ensure_msl_installed()
        {
            log::info!("[ModelicaCompiler] `{model_name}` still had unresolved refs — installed MSL, retrying");
            result = self
                .session
                .compile_model_dae_strict_reachable_uncached_with_recovery(model_name);
        }

        still_compiling.store(false, Ordering::Relaxed);
        // No `join` — see spawn comment above. The thread is detached
        // and will exit on its own within one tick.

        log::info!(
            "[ModelicaCompiler] compile `{}` finished in {:.2}s ({})",
            model_name,
            t_total.elapsed().as_secs_f64(),
            if result.is_ok() { "OK" } else { "ERR" },
        );
        result
    }

    /// Does compiling `model_name` against the *current* session fail with
    /// an unresolved type/component reference (rumoca diagnostic code
    /// `ER002`)? This is the demand-driven gate's oracle: it distinguishes
    /// "needs a library" from "genuinely broken" using rumoca's **structured
    /// error code**, not message-string matching. Runs the report-returning
    /// strict pass, which reuses the session's already-resolved state — the
    /// cheap second pass rumoca documents — and is only ever taken on the
    /// compile error path before MSL has been installed.
    fn target_has_unresolved_refs(&mut self, model_name: &str) -> bool {
        let report = self
            .session
            .compile_model_strict_reachable_uncached_with_recovery(model_name);
        // ER002 = undefined reference (a type/component use rumoca can't
        // resolve); ER003 = base class not found (an `extends Modelica.…`
        // whose base is missing). Both mean "a symbol a library could
        // provide is absent" — exactly the demand-driven load trigger. A
        // model that `extends` an MSL class hits ER003, not ER002, so the
        // gate must accept both or `extends`-only models never load MSL.
        report
            .failures
            .iter()
            .any(|f| matches!(f.error_code.as_deref(), Some("ER002") | Some("ER003")))
    }

    /// Access the underlying `rumoca_compile::Session` — used by a
    /// test helper that needs to inspect loaded source roots.
    #[cfg(test)]
    pub fn session(&self) -> &Session {
        &self.session
    }

    /// Merge a Modelica source root into the live session so
    /// subsequent compiles can resolve its types. Used by the
    /// `LoadSourceRoot` worker command (`source_roots` lazy-load
    /// pipeline) — main thread sends this command before a Compile
    /// that depends on the library. Idempotent: rumoca dedups by
    /// `id`, so re-issuing for an already-loaded root is cheap.
    ///
    /// Blocks the worker thread for the duration of the parse:
    /// MSL warm-bundle ~1–3 s; cold parse 10–60 s. Other queued
    /// commands wait behind it.
    pub fn load_source_root(
        &mut self,
        id: &str,
        root_dir: &std::path::Path,
    ) -> rumoca_compile::compile::SourceRootLoadReport {
        // MSL fast path: a pre-parsed bundle (`parsed-msl.bin`,
        // ~316 MB) sits next to the MSL source tree, produced by
        // `msl_indexer`. Installing it via
        // `Session::replace_parsed_source_set` takes ~1–3 s vs the
        // 30+ s cold-parse path of `load_source_root_tolerant` over
        // 2847 .mo files. The same fast path already runs inside
        // [`ModelicaCompiler::new`]'s `preload_from_global`; we
        // duplicate it here so the lazy `LoadSourceRoot` worker
        // command also benefits when MSL is loaded on-demand
        // (i.e. after the compiler was created empty for non-MSL
        // models like Balloon).
        if id == "Modelica" {
            // Shared fast path with `preload_from_global`: install the
            // memoized pre-parsed bundle (native streams `parsed-msl.bin`
            // once per process; wasm uses the decoder slot) rather than
            // re-reading + re-deserialising the ~316 MB file here.
            if let Some((total, inserted)) = Self::install_parsed_msl(&mut self.session, id) {
                log::info!(
                    "[ModelicaCompiler] installed pre-parsed MSL bundle \
                     ({} of {} docs)",
                    inserted, total,
                );
                return rumoca_compile::compile::SourceRootLoadReport {
                    source_set_id: id.to_string(),
                    source_root_path: lunco_assets::msl_dir()
                        .join("parsed-msl.bin")
                        .display()
                        .to_string(),
                    parsed_file_count: total,
                    inserted_file_count: inserted,
                    cache_status: None,
                    cache_key: None,
                    cache_file: None,
                    diagnostics: Vec::new(),
                };
            }
        }
        self.session.load_source_root_tolerant(
            id,
            rumoca_compile::compile::SourceRootKind::DurableExternal,
            root_dir,
            None,
        )
    }

    /// Merge an in-memory source root (e.g. a bundled `.mo` file or
    /// a single workspace file) into the live session. Same
    /// idempotency + blocking semantics as
    /// [`Self::load_source_root`], but bytes are passed inline so
    /// callers without a real on-disk path can still install
    /// sources.
    ///
    /// `label` shows up in diagnostics as the "source root path"
    /// (rumoca convention: `"in-memory:<id>"`). `files` is a list
    /// of `(uri, source)` pairs; each `uri` is the filename rumoca
    /// will report errors against.
    pub fn load_source_root_in_memory(
        &mut self,
        id: &str,
        label: &str,
        files: Vec<(String, String)>,
    ) -> rumoca_compile::compile::SourceRootLoadReport {
        let file_count = files.len();
        let mut inserted = 0;
        for (uri, text) in &files {
            if self.session.add_document(uri, text).is_ok() {
                inserted += 1;
            }
        }
        rumoca_compile::compile::SourceRootLoadReport {
            source_set_id: id.to_string(),
            source_root_path: label.to_string(),
            parsed_file_count: file_count,
            inserted_file_count: inserted,
            cache_status: None,
            cache_key: None,
            cache_file: None,
            diagnostics: Vec::new(),
        }
    }
}

/// Convert a rumoca [`StrictCompileReport`] into the Diagnostics
/// panel's [`Diagnostic`](lunco_doc::Diagnostic) form.
///
/// A failure becomes *located* (click-to-source) only when its primary
/// label points at `user_uri` — diagnostics rooted in MSL / sibling
/// library files keep their message (suffixed with the originating
/// file name) but no line/column, so clicking never jumps the editor
/// to a file it isn't showing. Each message is prefixed with rumoca's
/// diagnostic code when present (`ED008`, `EI001`, …) so the panel
/// reads like a real compiler's output.
///
/// [`StrictCompileReport`]: rumoca_compile::compile::StrictCompileReport
fn diagnostics_from_strict_report(
    report: &rumoca_compile::compile::StrictCompileReport,
    user_uri: &str,
) -> Vec<lunco_doc::Diagnostic> {
    use lunco_doc::Diagnostic;
    report
        .failures
        .iter()
        .map(|f| {
            let message = match &f.error_code {
                Some(code) if !code.is_empty() => format!("[{code}] {}", f.error),
                _ => f.error.clone(),
            };
            // Resolve the primary span against the report's source map.
            // `source_map` is `None` only on malformed reports; spans in
            // dummy/compiler-generated sources resolve to `None` here.
            let resolved = f.primary_label.as_ref().and_then(|label| {
                let sm = report.source_map.as_ref()?;
                let (name, content) = sm.get_source(label.span.source)?;
                Some((name.to_string(), content.to_string(), label.span.start.0))
            });
            match resolved {
                Some((name, content, start)) if name == user_uri => {
                    let (line, column) =
                        crate::document::core::byte_offset_to_line_col(&content, start);
                    Diagnostic::error(message, Some(line), Some(column))
                }
                // Diagnostic in another file — name it so the user knows
                // where it came from, but leave it unlocated.
                Some((name, _, _)) => {
                    Diagnostic::message_only(format!("{message}  (in {name})"))
                }
                None => Diagnostic::message_only(message),
            }
        })
        .collect()
}

/// Convert a rumoca-sim runtime/lowering failure into located diagnostics for
/// the Diagnostics panel — the runtime counterpart of
/// [`diagnostics_from_strict_report`].
///
/// [`rumoca_sim::SimulationDiagnosticError`] is structured: it
/// carries a stable diagnostic code and (for the `SolveLowering` variant) a
/// source span via `source_span()`. We surface the code-prefixed `Display`
/// message and, when a span is present and lands inside the user's model
/// source, a clickable `(line, column)`. `Solver` runtime blow-ups have no
/// span and degrade to a single message-only row.
///
/// `source` must be the text those byte offsets index into — i.e. the source
/// that was compiled to the DAE. The compiled text is the *stripped* source
/// (`strip_input_defaults`, applied at the `seat_user_source` chokepoint), but
/// the strip BLANKS the binding bytes in place instead of deleting them, so it
/// is length-preserving: every offset in the stripped source indexes the same
/// character in the caller's raw buffer, and click-to-source stays correct.
fn diagnostics_from_sim_error(
    err: &rumoca_sim::SimulationDiagnosticError,
    source: &str,
) -> Vec<lunco_doc::Diagnostic> {
    use lunco_doc::Diagnostic;
    let message = format!("[{}] {err}", err.diagnostic_code());
    match err.source_span() {
        // `start.0` is a 0-based UTF-8 byte offset; only trust it when it
        // lands inside the buffer we're resolving against (guards against a
        // span rooted in a library/compiler-generated source).
        Some(span) if span.start.0 <= source.len() => {
            let (line, column) =
                crate::document::core::byte_offset_to_line_col(source, span.start.0);
            vec![Diagnostic::error(message, Some(line), Some(column))]
        }
        _ => vec![Diagnostic::message_only(message)],
    }
}


#[cfg(feature = "ui")]
pub mod ui;

/// Bundled Modelica models for web deployment.
/// Available on all targets, but primarily used for wasm builds.
pub mod models;
pub mod msl_remote;
pub mod source_asset;

/// Tuning resource for [`ModelicaPlugin`] / [`ui::ModelicaUiPlugin`].
///
/// Most apps want every panel + the first-run help overlay (lunica is
/// that app; this is the default). Sandbox-class apps embed the
/// workbench as a *secondary* workspace and want the panels but not the
/// onboarding coach-marks — they insert a customised value before
/// adding `ModelicaPlugin`:
///
/// ```ignore
/// app.insert_resource(lunco_modelica::ModelicaUiConfig {
///     include_help_overlay: false,
///     include_welcome_panel: false,
///     ..default()
/// });
/// app.add_plugins(lunco_modelica::ModelicaPlugin);
/// ```
#[derive(bevy::prelude::Resource, Clone, Debug)]
pub struct ModelicaUiConfig {
    /// First-run multi-screen help overlay (Help → Show Tour, F1).
    /// Defaults true — lunica's onboarding entry point.
    pub include_help_overlay: bool,
    /// Landing-page Welcome panel with bundled-example learning paths.
    /// Defaults true. Off for sandbox-class embeds where Welcome would
    /// look out of place inside a 3D-physics demo.
    pub include_welcome_panel: bool,
}

impl Default for ModelicaUiConfig {
    fn default() -> Self {
        Self {
            include_help_overlay: true,
            include_welcome_panel: true,
        }
    }
}
pub mod msl_settings;
/// The MSL **indexer** — a host-side tool, not a runtime component: it walks the
/// on-disk MSL tree, parses every `.mo`, and emits `msl_index.json` + the
/// pre-parsed `parsed-msl.bin` bundle. It is `std::fs`-shaped by definition and
/// has no wasm caller — the browser never *builds* an index, it *consumes* the
/// artifacts this produces (`msl_remote` fetches the bundle over HTTP and
/// installs it via `install_global_parsed_msl`). It used to be an unconditional
/// `pub mod`, so ~1.6k lines of dead directory-walking code shipped in the wasm
/// bundle and tripped the wasm lint. Native-gated now: the web MSL path is
/// `msl_remote`, and this is the thing that makes its input.
#[cfg(not(target_arch = "wasm32"))]
pub mod indexer;
pub mod sim_stream;
pub mod worker;
pub mod experiments_runner;

/// Bevy resource wrapping the singleton [`experiments_runner::ModelicaRunner`].
/// Stored as `Arc` so UI panels can clone the handle and call
/// `run_fast` from event handlers without holding a `ResMut` borrow.
#[derive(Resource, Clone)]
pub struct ModelicaRunnerResource(pub std::sync::Arc<experiments_runner::ModelicaRunner>);
/// Wasm-only Web Worker transport — relays `ModelicaCommand` /
/// `ModelicaResult` between the main wasm instance and the off-thread
/// worker bundle so the UI never blocks on rumoca compile / step.
#[cfg(target_arch = "wasm32")]
pub mod worker_transport;
pub use worker::{
    ModelicaChannels, ModelicaCommand, ModelicaModel, ModelicaResult, handle_modelica_responses,
    spawn_modelica_requests,
};

#[cfg(feature = "lunco-api")]
pub mod api_queries;

// Always built — the UI (palette, inspector, canvas) dispatches these
// `ApplyModelicaOps` Reflect events directly. The module is named `api_*`
// because external HTTP callers also use it when `lunco-api` is enabled,
// but the events themselves carry no `lunco-api` dependency.
/// External JSON-RPC API handlers.
pub mod api;

/// Shareable model links (encode model source into a URL fragment).
pub mod model_share;
pub use sim_stream::{new_sim_stream, SimSnapshot, SimStream, VarHistory, SimSample};

/// UI-agnostic per-frame queue of live sim samples.
///
/// The core worker handler ([`worker::handle_modelica_responses`]) appends one
/// [`SimSampleBatch`] per processed step; the reactive UI layer
/// ([`ui::core_observers::drain_sim_samples_to_viz`]) drains it into
/// `lunco_viz`. This keeps plot-history capture OUT of the core handler — core
/// just emits samples; the UI projects them. A headless build has no drainer,
/// so the queue is bounded at the producer (samples past the cap are dropped —
/// there's no UI to plot them anyway).
#[derive(Resource, Default)]
pub struct SimSampleStream {
    pub batches: Vec<SimSampleBatch>,
}

/// UI-agnostic notice emitted by the core (compile lifecycle, worker crash,
/// …). The reactive UI console observer
/// ([`ui::core_observers::drain_notices_to_console`]) projects these into the
/// Console panel. Core never references the console type.
#[derive(Message, Clone)]
pub struct ModelicaNotice {
    pub level: NoticeLevel,
    pub text: String,
}

/// Severity of a [`ModelicaNotice`].
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum NoticeLevel {
    Info,
    Warn,
    Error,
}

/// Core request to (re)compile a model — emitted by the core stepper when a
/// model needs a stepper but has none yet (interactive "Run before compile").
/// The reactive UI layer ([`ui::core_observers::relay_compile_requests`])
/// translates it into the UI `CompileModel` command. Core stays UI-agnostic.
#[derive(Message, Clone)]
pub struct CompileRequested {
    pub doc: lunco_doc::DocumentId,
    pub class: Option<String>,
    pub force: bool,
    pub resume_after_compile: bool,
}

/// One sim step's observable samples for a single entity.
pub struct SimSampleBatch {
    pub entity: Entity,
    pub document: lunco_doc::DocumentId,
    pub time: f64,
    /// `outputs` followed by `detected_symbols` (signal name → value).
    pub samples: Vec<(String, f64)>,
    pub is_new_model: bool,
    pub is_parameter_update: bool,
}

/// UI-thread registry of per-entity lock-free sim streams (Phase A
/// of the multi-sim architecture). On Compile the command observer
/// calls [`SimStreamRegistry::get_or_insert`] and ships a clone of
/// the returned `SimStream` to the worker thread; plots and
/// telemetry query the registry to get the same handle and render
/// without locking.
///
/// TODO(arch-phase-b): promote this into the full `SimRegistry`
///   keyed by `SimId` (not `Entity`) so non-Modelica backends can
///   publish snapshots through the same channel.
#[derive(Resource, Default)]
pub struct SimStreamRegistry {
    streams: std::collections::HashMap<Entity, SimStream>,
}

impl SimStreamRegistry {
    /// Existing stream for `entity`, or a freshly-created one. The
    /// returned handle is cheap to clone (Arc bump) and safe to
    /// share across threads.
    pub fn get_or_insert(&mut self, entity: Entity) -> SimStream {
        self.streams
            .entry(entity)
            .or_insert_with(sim_stream::new_sim_stream)
            .clone()
    }

    /// Returns the stream for `entity` if one has been registered.
    /// Readers never need mutable access — they just `load()` the
    /// `ArcSwap`.
    pub fn get(&self, entity: Entity) -> Option<&SimStream> {
        self.streams.get(&entity)
    }

    /// Drop the stream for `entity`. Called on despawn so stale
    /// snapshots don't pin memory.
    pub fn remove(&mut self, entity: Entity) {
        self.streams.remove(&entity);
    }
}

/// System sets for Modelica stepping in [`FixedUpdate`].
///
/// These sets let downstream code (e.g., balloon_setup) order its sync systems
/// relative to the Modelica worker communication.
#[derive(SystemSet, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ModelicaSet {
    /// Receive async results from the worker thread.
    HandleResponses,
    /// Send the next step command to the worker thread.
    SpawnRequests,
}

/// Bevy plugin for Modelica integration.
///
/// Sets up the background worker thread, channel resources, and response systems.
/// Modelica stepping runs in [`FixedUpdate`] so all co-simulation engines share
/// the same fixed timestep.
#[cfg(feature = "ui")]
pub struct ModelicaPlugin;

/// Headless variant of [`ModelicaPlugin`] without UI panels.
///
/// Use in tests and non-windowed binaries. Starts the worker, inserts channels,
/// schedules stepping systems, but skips `ModelicaUiPlugin`.
pub struct ModelicaCorePlugin;

impl Plugin for ModelicaCorePlugin {
    fn build(&self, app: &mut App) {
        build_modelica_core(app);
    }
}

#[cfg(feature = "ui")]
impl Plugin for ModelicaPlugin {
    fn build(&self, app: &mut App) {
        // The Modelica UI experience requires both core logic and plotting.
        // Enforce the dependency chain by adding them here.
        if !app.is_plugin_added::<ModelicaCorePlugin>() {
            app.add_plugins(ModelicaCorePlugin);
        }
        if !app.is_plugin_added::<lunco_viz::LuncoVizPlugin>() {
            app.add_plugins(lunco_viz::LuncoVizPlugin);
        }

        // PR-A: inventory every source root the workbench can load
        // into a rumoca compile session. No loads yet — the registry
        // just enumerates so PR-B's gate has something to look up.
        app.insert_resource(source_roots::SourceRootRegistry::build());
        // A mounted twin may ship its own Modelica packages under `<twin>/models`;
        // load them into the compile session so twin-authored programs resolve their
        // imports (the shipped `LunCo` library is seated by the compiler itself).
        app.add_systems(Update, source_roots::load_twin_source_roots);
        app.add_plugins(ui::ModelicaUiPlugin);
        app.add_plugins(lunco_doc_bevy::ViewSyncPlugin);
        // Self-register with the workbench's plugin-driven document-
        // kind registry so File→New, the file picker, the library
        // browser, and `twin.toml` parsers all see Modelica without
        // any central edit. Init the resource defensively in case
        // the workbench plugin hasn't been added yet.
        app.init_resource::<lunco_twin::DocumentKindRegistry>();
        let mut registry = app
            .world_mut()
            .resource_mut::<lunco_twin::DocumentKindRegistry>();
        registry.register(
            lunco_twin::DocumentKindId::new("modelica"),
            lunco_twin::DocumentKindMeta {
                display_name: "Modelica Model".into(),
                extensions: vec!["mo"],
                can_create_new: true,
                default_filename: Some("NewModel.mo"),
                uri_scheme: Some("modelica"),
                manifest_section: Some("modelica"),
            },
        );
        // Install the user-facing indentation default for the
        // pretty-printer. The library-level default is two-space so
        // pure-Rust tests have predictable output; the workbench UI
        // wants tabs (matches Dymola / MSL hand-authored style).
        // Users can override at runtime via a settings panel or
        // script by calling `pretty::set_options` again.
        pretty::set_options(pretty::PrettyOptions::tabs());
    }
}

/// One-call workbench bundle — the canonical "lunica IDE" wiring.
///
/// Everything the Modelica workbench needs to behave **identically**
/// whether it runs standalone (`lunica`, native or wasm) or embedded as a
/// host app's workspace (sandbox's "Design" tab) lives here, so there is
/// exactly one place to fix and no second site to drift against.
///
/// Bundles:
///   - [`lunco_workbench::WorkbenchPlugin`] (added only if the host
///     hasn't already — sandbox adds it early in its own chain);
///   - the passed [`ModelicaUiConfig`];
///   - [`ModelicaPlugin`] (panels + core + viz);
///   - **wasm-only**: the JS clipboard bridge ([`ui::wasm_clipboard`]),
///     localStorage autosave ([`ui::wasm_autosave`]), and the off-thread
///     compile worker ([`worker_transport::install_worker`]).
///
/// History: before this existed, `lunica_web.rs` and `sandbox.rs` each
/// re-wired the workbench by hand and drifted — the sandbox embed shipped
/// with no clipboard bridge (paste broken) and no autosave (reload lost
/// docs), while neither standalone web path nor sandbox stayed in sync on
/// the worker/UI-config knobs. Host apps select the embed flavour via the
/// `config` field:
///
/// ```ignore
/// app.add_plugins(lunco_modelica::ModelicaWorkbenchPlugin {
///     config: lunco_modelica::ModelicaUiConfig {
///         include_help_overlay: false,
///         ..Default::default()
///     },
/// });
/// ```
///
/// App-global frame pacing (`WinitSettings`, `Time<Virtual>` cap,
/// `ClearColor`) is deliberately **not** owned here — Bevy always inserts
/// defaults for those resources so an "insert-if-absent" guard can't tell
/// a host's choice from the default. Those stay an app-shell concern.
#[cfg(feature = "ui")]
#[derive(Default)]
pub struct ModelicaWorkbenchPlugin {
    /// UI knobs (help overlay, welcome panel). Defaults to the full
    /// lunica onboarding experience; embeds typically disable the
    /// help overlay.
    pub config: ModelicaUiConfig,
}

#[cfg(feature = "ui")]
impl Plugin for ModelicaWorkbenchPlugin {
    fn build(&self, app: &mut App) {
        if !app.is_plugin_added::<lunco_workbench::WorkbenchPlugin>() {
            app.add_plugins(lunco_workbench::WorkbenchPlugin);
        }
        app.insert_resource(self.config.clone());
        app.add_plugins(ModelicaPlugin);

        // Web-only affordances. Absent on native (native uses the OS
        // clipboard and a real worker thread):
        //  - clipboard: document-level capture-phase copy/cut/paste that
        //    pre-empts bevy_egui's broken async wasm clipboard pipeline.
        //  - autosave: persists Untitled / dirty docs to localStorage so
        //    a page reload doesn't silently lose work.
        #[cfg(target_arch = "wasm32")]
        {
            app.add_plugins(ui::wasm_clipboard::WasmClipboardPlugin);
            app.add_plugins(ui::wasm_autosave::WasmAutosavePlugin);
        }

        // Shareable model links — `CopyShareLink` clipboard command (all
        // platforms) + the wasm boot loader that opens a model carried in
        // the page URL fragment. Cross-platform: the command works on
        // native too (copies a public link).
        app.add_plugins(ui::model_share::ModelSharePlugin);

        // Off-thread Modelica worker. wasm32 has no real threads, so an
        // inline rumoca *compile* (seconds for non-trivial models) freezes the
        // render loop. The worker pool handles that heavy compile/run work — but
        // it is NOT spawned here. Spawning it eagerly at boot is a cold compile
        // of each ~60 MB worker bundle that can take tens of seconds on a weak
        // machine, and the diagram must not wait on it. We only register the
        // worker URL now; `worker_transport::ensure_pool_spawned` spawns the
        // pool the first time a compile/run is requested. Parsing-for-diagram
        // runs on the main thread until a worker is warm (see
        // `dispatch_parse_to_worker`), so the model renders immediately.
        #[cfg(target_arch = "wasm32")]
        worker_transport::register_worker_url("./worker/worker_bootstrap.js");
    }
}

fn build_modelica_core(app: &mut App) {
    let (tx_cmd, rx_cmd) = unbounded();
    let (tx_res, rx_res) = unbounded();

    // Ensure MSL remote management is present (fetching, settings, status).
    // The domain is incomplete without MSL access.
    if !app.is_plugin_added::<msl_remote::MslRemotePlugin>() {
        app.add_plugins(msl_remote::MslRemotePlugin);
    }

    // Register the `.mo` asset loader so domain code can fetch source
    // through `AssetServer::load(...)` instead of `std::fs::read_to_string`.
    // See `docs/architecture/40-asset-io.md`.
    if !app.is_plugin_added::<source_asset::ModelicaSourceAssetPlugin>() {
        app.add_plugins(source_asset::ModelicaSourceAssetPlugin);
    }

    let msl = msl_dir();
    if msl.exists() {
        if let Ok(abs_path) = std::fs::canonicalize(&msl) {
            std::env::set_var("MODELICAPATH", abs_path.to_string_lossy().to_string());
        }
    }

    // Point rumoca at the workspace's shared `.cache/rumoca/`, the
    // same one `modelica_run` and `msl_indexer` use. Without this
    // alignment, the workbench reads XDG default (`~/.cache/rumoca`)
    // while the CLI tools warm `<workspace>/.cache/rumoca` —
    // `msl_indexer --warm` then does NOTHING for first workbench
    // compile, which stretches from ~12 s (warm) to 13+ minutes (cold,
    // observed). Honor an externally-set `RUMOCA_CACHE_DIR` if the
    // caller wants a sandboxed location (CI, tests).
    //
    // Historical note: earlier versions deliberately left this
    // unset to share with `modelica_tester` (which used XDG too).
    // The new `modelica_run` / `msl_indexer` CLI tools standardised
    // on workspace, and the workbench needs to follow suit so a
    // single `--warm` pass benefits every tool.
    #[cfg(not(target_arch = "wasm32"))]
    if std::env::var_os("RUMOCA_CACHE_DIR").is_none() {
        let target = lunco_assets::cache_dir().join("rumoca");
        std::env::set_var("RUMOCA_CACHE_DIR", &target);
        log::info!(
            "[ModelicaPlugin] using rumoca cache at {} (set RUMOCA_CACHE_DIR to override)",
            target.display(),
        );
    }

    #[cfg(not(target_arch = "wasm32"))]
    {
        thread::spawn(move || {
            worker::modelica_worker(rx_cmd, tx_res);
        });
    }

    // On wasm we still hold the inline worker resource as a fallback for
    // pages that haven't loaded the off-thread worker bundle (e.g. local
    // dev where the worker JS file is missing). The Web Worker transport,
    // when wired up by the binary's startup code via
    // `worker_transport::install_worker`, takes precedence — it intercepts
    // commands via its own pump system and ships them to the worker
    // bundle, bypassing the inline path entirely.
    #[cfg(target_arch = "wasm32")]
    {
        app.insert_resource(worker::InlineWorker::default());
    }

    #[cfg(not(target_arch = "wasm32"))]
    app.insert_resource(ModelicaChannels { tx: tx_cmd, rx: rx_res });
    #[cfg(target_arch = "wasm32")]
    {
        // Hand the result-side sender to the worker_transport so the JS
        // `onmessage` callback can deliver decoded results into the same
        // channel the existing `handle_modelica_responses` system drains.
        // Cheap to clone; the original still goes into ModelicaChannels.
        let _ = worker_transport::register_result_sender(tx_res.clone());
        // Same trick on the command side so the JS test bridge can post
        // commands without going through the UI.
        let _ = worker_transport::register_command_sender(tx_cmd.clone());
        app.insert_resource(ModelicaChannels { tx: tx_cmd, rx: rx_res, rx_cmd, tx_res });
    }

    app.init_resource::<crate::state::WorkbenchState>();
    app.init_resource::<SimStreamRegistry>();
    app.init_resource::<SimSampleStream>();
    app.add_message::<ModelicaNotice>();
    app.add_message::<CompileRequested>();

    // ── Document foundation (moved out of the UI plugin so a headless server
    // journals + replicates Modelica edits, not just the GUI) ──────────────
    // The registry (source-of-truth for open `.mo` docs), the egui-free edit
    // funnel (`ModelicaApiEditPlugin` — already UI-free), the A3 journal-wire
    // auto-bridge (`wire_modelica_journal_handle`, reactive/once), and the
    // lifecycle-event drain. `ModelicaUiPlugin` no longer registers these; it
    // adds core first, so the GUI still gets them. Guarded/idempotent so the
    // UI's own `WorkbenchState`/registry init (a legacy safety net) is a no-op.
    app.init_resource::<crate::state::ModelicaDocumentRegistry>();
    if !app.is_plugin_added::<crate::api::ModelicaApiEditPlugin>() {
        app.add_plugins(crate::api::ModelicaApiEditPlugin);
    }
    app.add_systems(Update, crate::doc_ops::drain_document_changes);
    app.add_systems(
        Update,
        crate::doc_ops::wire_modelica_journal_handle
            .run_if(resource_added::<lunco_doc_bevy::JournalResource>),
    );

    // In-app rhai scripting runtime: `RunScenario` (attach + hot-reload a
    // scenario to an entity), the `cmd()`/prelude world-bridge, and the REPL.
    // This is what lets the workbench be DRIVEN by scripts and what the
    // rhai-authored lunica tutorials run on. `LunCoScriptingPlugin` self-supplies
    // the transport-free command core, so this works with NO API server —
    // scripting stays independent of the `lunco-api` feature. Guarded/idempotent.
    #[cfg(feature = "scripting")]
    if !app.is_plugin_added::<lunco_scripting::LunCoScriptingPlugin>() {
        app.add_plugins(lunco_scripting::LunCoScriptingPlugin);
    }

    // Experiments / Fast Run: backend-agnostic registry + this crate's
    // ModelicaRunner binding. UI for the Run buttons and Experiments
    // panel is layered in `ui::experiments_panel` (Step 5+).
    app.add_plugins(lunco_experiments::ExperimentsPlugin);
    app.insert_resource(ModelicaRunnerResource(
        std::sync::Arc::new(experiments_runner::ModelicaRunner::new()),
    ));
    app.init_resource::<experiments_runner::PendingHandles>();
    app.init_resource::<experiments_runner::ExperimentDrafts>();
    app.init_resource::<experiments_runner::ExperimentSources>();
    app.init_resource::<experiments_runner::PlaybackEntities>();
    // Persisted concurrency cap for parallel Fast Runs (settings.json
    // `experiments.max_parallel`; None = platform auto). The apply system
    // pushes it into the runner on startup and on later edits.
    use lunco_settings::AppSettingsExt;
    app.register_settings_section::<experiments_runner::ExperimentSettings>();
    app.add_systems(
        Update,
        (
            experiments_runner::apply_experiment_settings,
            experiments_runner::drain_pending_handles,
        ),
    );

    // Keep the winit event loop pumping at full speed while any sim
    // is active, even when the window loses focus. Otherwise the
    // app's idle `unfocused_mode` (lunica defaults to
    // `reactive_low_power(1s)`) throttles `FixedUpdate` and the
    // Modelica/cosim stepper crawls. Restores the binary's
    // configured idle mode the moment all sims pause/finish.
    app.add_systems(Update, sim_focus_pace);

    app.configure_sets(
        FixedUpdate,
        (ModelicaSet::HandleResponses, ModelicaSet::SpawnRequests).chain(),
    );

    // The model-vs-world clock divergence diagnostic (A3): written every fixed
    // tick by `spawn_modelica_requests`, read by anything that wants to know
    // whether the co-simulation is actually keeping up.
    app.init_resource::<worker::CosimLag>();

    app.register_type::<ModelicaModel>()
        .add_observer(worker::on_remove_modelica)
        .add_systems(FixedUpdate, (
            handle_modelica_responses.in_set(ModelicaSet::HandleResponses),
            spawn_modelica_requests.in_set(ModelicaSet::SpawnRequests),
        ));

    // Global frame-time tracker. Logs every Update tick that exceeds
    // a threshold AND every tick within a 5-second window after the
    // last Modelica edit. The canvas-render-internal SLOW frame
    // instrumentation only caught time spent inside one panel; this
    // catches main-thread blocking in ANY system on the Bevy schedule
    // (other panels, observers, drive_*_cache, etc.).
    app.init_resource::<FrameTimeProbe>();
    app.add_systems(bevy::prelude::First, frame_time_probe_start);
    app.add_systems(bevy::prelude::PreUpdate, frame_time_probe_pre_update_end);
    app.add_systems(bevy::prelude::Update, frame_time_probe_update_end);
    app.add_systems(bevy::prelude::PostUpdate, frame_time_probe_post_update_end);
    app.add_systems(bevy::prelude::Last, frame_time_probe_end);

    #[cfg(target_arch = "wasm32")]
    {
        // Command dispatch on wasm. `pump_commands_to_worker` is the primary
        // drainer: on a queued command it lazily spawns the worker pool and
        // ships the command off-thread. It is ordered BEFORE
        // `inline_worker_process` so that, whenever the pool spawns, the inline
        // fallback sees an empty queue and no-ops. The inline (main-thread)
        // path only does work when `pump_commands_to_worker` declines — i.e.
        // the worker bundle failed to spawn — so a missing/blocked worker still
        // compiles (just on the main thread).
        app.add_systems(
            Update,
            worker_transport::pump_commands_to_worker
                .before(worker::inline_worker_process),
        );
        // Re-seed MSL into workers respawned after a crash, deferred so the
        // ~165 MB bundle isn't re-allocated on the (memory-starved) crash
        // stack. Cheap no-op when nothing is pending.
        app.add_systems(Update, |_world: &mut World| {
            worker_transport::pump_worker_respawns();
        });
        app.add_systems(Update, worker::inline_worker_process);
        app.add_systems(Update, crate::state::update_file_load_result);
        // Drain Web-Worker RunUpdate streams into the runner's
        // RunHandle receivers and clear the runner's busy flag on
        // terminal updates. Cheap when no run is in flight.
        app.add_systems(Update, |_world: &mut World| {
            experiments_runner::pump_wasm_forwarders();
        });
    }
}

/// Keep winit's `unfocused_mode` pegged at `Continuous` while any
/// sim is active (interactive `ModelicaModel { paused: false }` or
/// a non-empty `PendingHandles`), otherwise restore the binary's
/// idle setting. The first invocation snapshots whatever the
/// binary inserted into `WinitSettings` so we can faithfully restore
/// it later — the modelica plugin does not pick the idle policy
/// itself, just respects what the host app chose. No-op when the
/// app is headless (no `WinitSettings` resource).
#[cfg(all(not(target_arch = "wasm32"), feature = "ui"))]
fn sim_focus_pace(
    settings: Option<ResMut<bevy::winit::WinitSettings>>,
    pending: Option<Res<experiments_runner::PendingHandles>>,
    models: Query<&worker::ModelicaModel>,
    keep_awake: Option<Res<lunco_core::KeepAwake>>,
    mut idle: Local<Option<bevy::winit::UpdateMode>>,
) {
    let Some(mut settings) = settings else { return };
    if idle.is_none() {
        *idle = Some(settings.unfocused_mode);
    }
    // This system runs every frame and is the last writer of `unfocused_mode`, so
    // it must honour other subsystems' pacing intent rather than stomp it: a crate
    // that merely sets `WinitSettings` would have its choice reverted here on the
    // next frame. Offline frame recording is the case that matters — an unattended
    // capture has no focused window and is not a Modelica sim, so without this it
    // gets throttled to the reactive timer (~1 s/frame instead of ~50 ms).
    let sim_active = pending.map(|p| !p.0.is_empty()).unwrap_or(false)
        || models.iter().any(|m| !m.paused && m.is_compiled)
        || keep_awake.map(|k| k.wanted()).unwrap_or(false);
    let desired = if sim_active {
        bevy::winit::UpdateMode::Continuous
    } else {
        idle.expect("snapshot set above")
    };
    if settings.unfocused_mode != desired {
        settings.unfocused_mode = desired;
    }
}

// No-op when there's no winit `WinitSettings` to pace: on wasm (the rAF loop
// drives updates regardless of focus) and on a headless `--no-ui` server (no
// winit compiled in). Keeps the symbol present so `add_systems` compiles.
#[cfg(any(target_arch = "wasm32", not(feature = "ui")))]
fn sim_focus_pace() {}

/// Global frame-time probe — start of frame.
fn frame_time_probe_start(mut probe: ResMut<FrameTimeProbe>) {
    let now = web_time::Instant::now();
    probe.frame_start = Some(now);
    probe.pre_update_start = Some(now);
}

fn frame_time_probe_pre_update_end(mut probe: ResMut<FrameTimeProbe>) {
    let now = web_time::Instant::now();
    probe.pre_update_ms = probe
        .pre_update_start
        .map(|t| now.duration_since(t).as_secs_f64() * 1000.0)
        .unwrap_or(0.0);
    probe.update_start = Some(now);
}

fn frame_time_probe_update_end(mut probe: ResMut<FrameTimeProbe>) {
    let now = web_time::Instant::now();
    probe.update_ms = probe
        .update_start
        .map(|t| now.duration_since(t).as_secs_f64() * 1000.0)
        .unwrap_or(0.0);
    probe.post_update_start = Some(now);
}

fn frame_time_probe_post_update_end(mut probe: ResMut<FrameTimeProbe>) {
    let now = web_time::Instant::now();
    probe.post_update_ms = probe
        .post_update_start
        .map(|t| now.duration_since(t).as_secs_f64() * 1000.0)
        .unwrap_or(0.0);
    probe.last_start = Some(now);
}

/// Global frame-time probe — end of frame. Logs the total Bevy
/// schedule time and (if applicable) flags whether we're inside the
/// post-edit window so per-edit hitches anywhere in the app surface.
fn frame_time_probe_end(mut probe: ResMut<FrameTimeProbe>) {
    let now = web_time::Instant::now();
    let last_ms = probe
        .last_start
        .map(|t| now.duration_since(t).as_secs_f64() * 1000.0)
        .unwrap_or(0.0);
    let Some(start) = probe.frame_start else { return };
    let dt_ms = now.duration_since(start).as_secs_f64() * 1000.0;
    let in_window = probe
        .last_edit
        .map(|t| t.elapsed().as_secs_f64() < 5.0)
        .unwrap_or(false);
    // Default fully off. egui idles at ~30 fps and even a long
    // compile / parse can run for seconds, so any unconditional
    // "hard hitch" threshold floods the console during normal use.
    // Enable explicitly with `LUNCO_FRAME_PROBE=1` (any non-empty
    // value) when investigating a specific freeze.
    let probe_enabled = std::env::var_os("LUNCO_FRAME_PROBE").is_some();
    if probe_enabled && (dt_ms > 30.0 || in_window) {
        bevy::log::info!(
            "[FrameTimeProbe] total={dt_ms:.0}ms pre={:.0} update={:.0} post={:.0} last={last_ms:.0}{}",
            probe.pre_update_ms,
            probe.update_ms,
            probe.post_update_ms,
            if in_window { " (post-edit window)" } else { "" }
        );
    }
    probe.frame_start = None;
}

/// Stamp the `last_edit` timestamp from anywhere that mutates a
/// document. The `apply_ops` site in `canvas_diagram` calls this so
/// the post-edit window covers any frame after a user edit.
pub fn frame_time_probe_stamp_edit(world: &mut World) {
    if let Some(mut probe) = world.get_resource_mut::<FrameTimeProbe>() {
        probe.last_edit = Some(web_time::Instant::now());
    }
}

#[derive(Resource, Default)]
pub struct FrameTimeProbe {
    frame_start: Option<web_time::Instant>,
    pre_update_start: Option<web_time::Instant>,
    update_start: Option<web_time::Instant>,
    post_update_start: Option<web_time::Instant>,
    last_start: Option<web_time::Instant>,
    pre_update_ms: f64,
    update_ms: f64,
    post_update_ms: f64,
    last_edit: Option<web_time::Instant>,
}


// ---------------------------------------------------------------------------
// Re-export AST extraction for public API compatibility
// ---------------------------------------------------------------------------
// These functions live in `ast_extract` but are re-exported here so external
// callers (workbench binaries, UI panels) can import from the crate root.
pub use ast_extract::{
    extract_model_name,
    extract_model_name_from_ast,
    extract_parameters,
    extract_parameters_from_ast,
    extract_inputs_with_defaults,
    extract_inputs_with_defaults_from_ast,
    hash_content,
};
// `strip_input_defaults` is already imported via `use self::ast_extract::strip_input_defaults`
// above and is available publicly through the `pub mod ast_extract` declaration.

// ---------------------------------------------------------------------------
// Re-export diagram types for public API
// ---------------------------------------------------------------------------
pub use diagram::{
    DiagramType,
    ModelicaComponentBuilder,
    list_class_names,
};

#[derive(Component, Reflect, Default)]
pub struct ModelicaInput { pub variable_name: String, pub value: f64 }

#[derive(Component, Reflect, Default)]
pub struct ModelicaOutput { pub variable_name: String, pub value: f64 }

#[cfg(test)]
mod observables_smoke {
    use super::*;
    use lunco_experiments::RunBounds;
    use rumoca_sim::SimulationSession;

    /// End-to-end smoke test for the observables pipeline: compile the
    /// bundled RocketEngine, run one step at full throttle, and assert
    /// every algebraic observable shows up with a physically-sensible
    /// value in [`worker::collect_stepper_observables`]. Protects against
    /// (a) bumping rumoca to a version that drops `EliminationResult`
    ///     from the stepper again, and
    /// (b) reintroducing a Boolean intermediate in the bundled model
    ///     that rumoca's elimination pass can't reconstruct.
    ///
    /// H12: this test was `#[cfg(any())]`-disabled behind a FIXME claiming
    /// `collect_stepper_observables` had been "removed during the SnapshotStream
    /// refactor". It was not removed — it lives in `worker.rs` and is on the hot
    /// path of every Step (it is what fills `ModelicaResult.outputs`). The stale
    /// FIXME was hiding the one test that covers it. Re-enabled against its real
    /// home.
    ///
    /// STATUS: re-enabling it (the FIXME was false — `collect_stepper_observables`
    /// was never removed) proved the thing it was written to catch is REALLY
    /// HAPPENING, so it is `#[ignore]`d with the truth rather than silently
    /// `cfg(any())`-deleted, matching how this crate already pins its other
    /// upstream-rumoca failures.
    ///
    /// Two separate defects, both real:
    ///  1. `m_dot = if m_prop > 0.0 and throttle > 0.01 then m_dot_max * throttle
    ///     else 0.0` reconstructs as **0** at throttle = 1. The model's own comment
    ///     says the Boolean was inlined *specifically* to dodge rumoca's
    ///     "continuous substitutions only" reconstructor — that workaround does not
    ///     work: the conditional still reads 0, which zeroes `thrust` and
    ///     `p_chamber` with it. Every algebraic observable behind an `if` is dead.
    ///  2. The `isp` assertion is stale: it expects `v_e = 2900`, but
    ///     `assets/models/RocketEngine.mo` has said `v_e = 3100.0` for some time.
    ///     Fixed below, but it could never have passed either.
    ///
    /// TODO(rumoca-observables): fix the elimination reconstructor (or stop
    /// reporting conditional algebraics as observables instead of lying with a 0),
    /// then remove the `#[ignore]`.
    #[test]
    #[ignore = "rumoca's elimination reconstructor evaluates conditional algebraics as 0 — m_dot/thrust/p_chamber read 0 at full throttle. Real defect, see TODO(rumoca-observables)."]
    fn rocket_engine_observables_round_trip() {
        let raw = crate::models::get_model("RocketEngine.mo").expect("bundled RocketEngine.mo");
        let mut c = ModelicaCompiler::new();
        // `compile_str` strips bound-input defaults itself (the chokepoint).
        let r = c.compile_str("RocketEngine", raw, "RocketEngine.mo")
            .expect("compile ok");
        // Options come from the canonical builder, never `SimOptions::default()`:
        // the session clamps every advance at `t_end`, whose default is 1.0.
        let opts = crate::experiments_runner::stepper_options_from_bounds(&RunBounds {
            t_start: 0.0,
            t_end: 10.0,
            ..Default::default()
        });
        let mut stepper = SimulationSession::new(&r.dae, opts).expect("stepper ok");
        stepper.set_input("throttle", 1.0).expect("throttle is an input");
        stepper.step(0.01).expect("step ok");

        let obs = worker::collect_stepper_observables(&stepper);
        let by_name: std::collections::HashMap<_, _> =
            obs.into_iter().collect();

        for name in ["m_prop", "impulse", "m_dot", "thrust", "p_chamber", "isp"] {
            assert!(by_name.contains_key(name), "missing observable: {name}");
        }
        assert!(by_name["m_dot"] > 0.0,
            "m_dot should be nonzero at throttle=1, got {}", by_name["m_dot"]);
        assert!(by_name["thrust"] > 0.0,
            "thrust should be nonzero, got {}", by_name["thrust"]);
        assert!(by_name["p_chamber"] > 0.0,
            "p_chamber should be nonzero, got {}", by_name["p_chamber"]);
        // v_e = 3100.0 in assets/models/RocketEngine.mo (the old 2900 here was stale).
        assert!((by_name["isp"] - 3100.0 / 9.80665).abs() < 1e-3,
            "isp should equal v_e / g, got {}", by_name["isp"]);
    }

    /// Verifies that `"..."` description strings (MLS §A.2.5) survive
    /// into the per-doc [`crate::index::ModelicaIndex`] — that's what
    /// panels read for hover tooltips. If this regresses, Telemetry
    /// tooltips go dark.
    #[test]
    fn rocket_engine_descriptions_populate() {
        let raw = crate::models::get_model("RocketEngine.mo").expect("bundled RocketEngine.mo");
        let ast = rumoca_phase_parse::parse_to_ast(raw, "RocketEngine.mo")
            .expect("parses");
        let mut index = crate::index::ModelicaIndex::new();
        index.rebuild_from_ast(&ast, raw);
        for (var, needle) in [
            ("m_dot_max", "mass flow"),
            ("throttle",  "Throttle"),
            ("m_prop",    "Propellant"),
            ("thrust",    "Thrust"),
        ] {
            let entry = index
                .find_component_by_leaf(var)
                .unwrap_or_else(|| panic!("no component '{var}' in index"));
            assert!(
                entry.description.contains(needle),
                "'{var}' description should contain '{needle}', got: {:?}",
                entry.description
            );
        }
    }

    // ─────────────────────────────────────────────────────────
    // MSL demand-driven compile tests
    // ─────────────────────────────────────────────────────────
    //
    // Run with: `cargo test -p lunco-modelica msl --nocapture`
    //
    // `msl_` tests require the MSL tree at `<cache>/msl/Modelica/`
    // (populated by our indexer). They skip with a stderr notice if
    // absent — CI can run the non-MSL subset unconditionally.
    //
    // The headline test `msl_compile_with_limpid_is_fast_and_succeeds`
    // exercises the full iterative demand-load pipeline: alias
    // resolution, rumoca error → missing-class regex, fs::read,
    // update_document, retry loop. A known-good MSL example that
    // used to hang for minutes is the sanity check; we assert the
    // happy path + print elapsed so regression to "minutes" is
    // obvious in the log even if the timing isn't asserted strictly
    // (test runner load is variable).

    fn msl_available() -> bool {
        lunco_assets::msl_source_root_path().is_some()
    }


    /// Trivial smoke test — compile a self-contained model with no
    /// MSL references. Shouldn't touch the iterative loop at all,
    /// verifies the plain-compile path works post-refactor.
    #[test]
    fn bare_model_compiles_without_msl() {
        let src = r#"
            model Bare
              Real x(start=1);
            equation
              der(x) = -x;
            end Bare;
        "#;
        let mut c = ModelicaCompiler::new();
        let r = c.compile_str("Bare", src, "Bare.mo")
            .expect("bare model must compile without MSL");
        // Just assert we got a DAE at all — shape details vary
        // by rumoca version.
        let _ = r.dae;
    }

    /// Headline: end-to-end demand-driven compile that pulls MSL
    /// classes via the iterative loop. A minimal LimPID-using model
    /// forces the compiler to iteratively resolve Continuous.LimPID
    /// → Interfaces.SISO → SI types → Icons → etc.
    ///
    /// **Asserts**:
    /// - compile succeeds
    /// - logs total elapsed time (paste-able into regression tracking)
    /// - iteration count reasonable (< 20 for a small closure)
    ///
    /// Skips with a print if MSL isn't installed locally.
    /// Known-failing — not a resolver issue. Compiles through the
    /// resolve phase cleanly (all `SI.*`, `Logical.*` refs are
    /// resolved via the lazy hook). Fails at DAE (ToDae phase)
    /// with `unresolved reference: ModelicaServices.Machine.eps`.
    /// Rumoca hardcodes `ModelicaServices.Machine` + `Modelica.Constants`
    /// as CONSTANT_PACKAGES
    /// (rumoca-phase-flatten/src/lib.rs:687-689); its lookup in
    /// the resolved tree doesn't find `ModelicaServices.Machine`
    /// even after we `update_document(ModelicaServices/package.mo)`.
    /// Fetch trace confirms the file lands in the session but
    /// rumoca's constant-package resolver still errors.
    ///
    /// Note: `msl_compile_pid_controller_example_succeeds` passes
    /// and *also* instantiates LimPID transitively — so the gap
    /// is specific to this minimal direct-instantiation shape, not
    /// to LimPID itself. Filed as a rumoca-internal issue.
    #[test]
    #[ignore = "rumoca CONSTANT_PACKAGES lookup can't find ModelicaServices.Machine even after the file is loaded"]
    fn msl_compile_tiny_limpid_model_is_fast() {
        if !msl_available() {
            eprintln!("skipping msl_compile_tiny_limpid_model_is_fast: \
                       MSL not at {:?}",
                lunco_assets::msl_source_root_path());
            return;
        }
        // Tiny model that references one MSL block — drags in the
        // transitive closure via the iterative loader. Kept inline
        // so the test doesn't depend on a user file.
        let src = r#"
            model TestLimPID
              import Modelica.Units.SI;
              parameter SI.Time Ti = 0.1;
              Modelica.Blocks.Continuous.LimPID ctrl(
                k = 1.0,
                Ti = Ti,
                yMax = 10.0
              );
            equation
              ctrl.u_s = 1.0;
              ctrl.u_m = 0.0;
            end TestLimPID;
        "#;
        let mut c = ModelicaCompiler::new();
        let t0 = web_time::Instant::now();
        let result = c.compile_str("TestLimPID", src, "TestLimPID.mo");
        let elapsed = t0.elapsed();
        eprintln!(
            "msl_compile_tiny_limpid_model_is_fast: elapsed {:.2}s, \
             result = {}",
            elapsed.as_secs_f64(),
            if result.is_ok() { "OK".to_string() } else {
                format!("ERR: {}", result.as_ref().err().unwrap())
            }
        );
        result.expect("compile must succeed after iterative MSL load");
    }

    /// Same shape, against the actual PID_Controller example
    /// extracted from `Blocks/package.mo`. Bigger closure —
    /// Mechanics.Rotational + Blocks.Continuous + KinematicPTP +
    /// sensors + Icons.
    ///
    /// With the lazy ExternalResolver hook in place this should
    /// work without any alias-table workaround; rumoca's own §5
    /// resolver walks the `within Modelica;` + enclosing package
    /// imports and calls us for the bytes. Kept as a *diagnostic*
    /// test: if it fails, the failure is either (a) a genuine
    /// rumoca MLS gap (PID is NOT in rumoca's 180-supported MSL
    /// targets list — it may be one of the 15 known-failing), or
    /// (b) a resolver miss our hook should have handled.
    #[test]
    fn msl_compile_pid_controller_example_succeeds() {
        if !msl_available() {
            eprintln!("skipping: MSL not available");
            return;
        }
        // Reference by fully-qualified name so rumoca's scope-walker
        // sees the enclosing `package Blocks` (which carries
        // `import Modelica.Units.SI;`). The earlier version of this
        // test sliced PID_Controller out of `Blocks/package.mo` and
        // fed it as a standalone class, which dropped the enclosing
        // package's imports — failure was a test-construction flaw
        // on our side, not a resolver or rumoca gap.
        let src = r#"
            model TestPID
              extends Modelica.Blocks.Examples.PID_Controller;
            end TestPID;
        "#;
        let mut c = ModelicaCompiler::new();
        let t0 = web_time::Instant::now();
        let result = c.compile_str("TestPID", src, "TestPID.mo");
        let elapsed = t0.elapsed();
        eprintln!(
            "msl_compile_pid_controller_example_succeeds: elapsed {:.2}s, \
             result = {}",
            elapsed.as_secs_f64(),
            if result.is_ok() { "OK".to_string() } else {
                format!("ERR (first 500 chars): {}",
                    result.as_ref().err().unwrap().chars().take(500).collect::<String>())
            }
        );
        result.expect("PID_Controller must compile after iterative MSL load");
    }

    /// End-to-end test against an MSL target rumoca *officially*
    /// claims to support (from `msl_simulation_targets_180.json` in
    /// rumoca-test-msl). This is the real acceptance test for the
    /// lazy-resolver architecture: rumoca's §5 resolver walks the
    /// scope, our `MslLazyResolver` supplies bytes on demand, a
    /// tiny wrapper model instantiates a known-good MSL example by
    /// fully-qualified name. If this fails, the loader architecture
    /// is broken. If it passes but PID_Controller fails, the delta
    /// is a rumoca MLS gap — not our problem.
    #[test]
    fn msl_compile_known_good_rotational_example() {
        if !msl_available() {
            eprintln!("skipping: MSL not available");
            return;
        }
        // Minimal wrapper — forces the resolver to pull in
        // Rotational.Examples.First and its entire transitive
        // closure (Rotational.Components, Interfaces, SI types,
        // Icons, …). References by fully-qualified name, which is
        // the scope-friendly form rumoca resolves cleanly.
        let src = r#"
            model TestRotFirst
              extends Modelica.Mechanics.Rotational.Examples.First;
            end TestRotFirst;
        "#;
        let mut c = ModelicaCompiler::new();
        let t0 = web_time::Instant::now();
        let result = c.compile_str("TestRotFirst", src, "TestRotFirst.mo");
        let elapsed = t0.elapsed();
        eprintln!(
            "msl_compile_known_good_rotational_example: elapsed {:.2}s, \
             result = {}",
            elapsed.as_secs_f64(),
            if result.is_ok() { "OK".to_string() } else {
                format!("ERR (first 800 chars): {}",
                    result.as_ref().err().unwrap().chars().take(800).collect::<String>())
            }
        );
        result.expect("Rotational.Examples.First (known-good MSL target) must compile");
    }

    /// Purely-qualified-name test. If this passes but
    /// `msl_compile_known_good_rotational_example` fails, the gap
    /// is unambiguously in rumoca's short-form scope walking
    /// (enclosing-package imports aren't reaching nested classes),
    /// not in our resolver.
    #[test]
    fn msl_fully_qualified_time_resolves() {
        if !msl_available() {
            eprintln!("skipping: MSL not available");
            return;
        }
        let src = r#"
            model TestFullyQualifiedSI
              parameter Modelica.Units.SI.Time Ti = 0.5;
              Real x(start=1);
            equation
              der(x) = -x / Ti;
            end TestFullyQualifiedSI;
        "#;
        let mut c = ModelicaCompiler::new();
        let t0 = web_time::Instant::now();
        let result = c.compile_str("TestFullyQualifiedSI", src, "Q.mo");
        let elapsed = t0.elapsed();
        eprintln!(
            "msl_fully_qualified_time_resolves: elapsed {:.2}s, result = {}",
            elapsed.as_secs_f64(),
            if result.is_ok() { "OK".into() } else {
                format!("ERR (first 800 chars): {}",
                    result.as_ref().err().unwrap().chars().take(800).collect::<String>())
            }
        );
        result.expect("fully-qualified SI.Time must compile");
    }
}




