#!/usr/bin/env python3
"""Regenerate the registered schema artifacts from schema.usda.

Two outputs, both derived — never hand-edited:
  - `generatedSchema.usda` — the layer a USD runtime registers
  - the `Types` block of `plugInfo.json` — the registry entry that makes each
    class RESOLVABLE by an external runtime (usdview / Omniverse / Pixar USD)

A class declared in `schema.usda` but absent from the `Types` block is
unresolvable by an external runtime — which would defeat the entire point of
codeless schemas over loose `customData`. Deriving the block from the source
makes that drift impossible by construction;
`schema::tests::every_schema_class_is_registered_in_pluginfo` is the backstop.


The schema library is CODELESS (`skipCodeGeneration = true`): the "generated"
file is not C++ codegen, it is the registered layer — `plugInfo.json` points a
USD runtime at it, and `lunco_usd::schema::SchemaRegistry` parses it at runtime.
Pixar's `usdGenSchema` produces it from `schema.usda`; this script is the
in-repo equivalent so the two files can never drift by hand-sync (the
documented trap: schema.usda is INERT, the generated file is what loads).

Transform (what usdGenSchema does that matters to a codeless consumer):
  - drop the core `subLayers` (usd/usdGeom/usdPhysics/... sources are vendored
    separately under `schema/core/` and ingested on their own)
  - drop the `inherits = </APISchemaBase>` / `</Typed>` arcs (the registry and
    codeless registration read flat class definitions)
  - keep everything else verbatim: class prims, `customData` (apiSchemaType,
    UI hints, lunco:unit), attribute types/defaults/variability, docs, comments

Usage:  python3 scripts/gen_schema.py         (rewrite the derived artifacts)
        python3 scripts/gen_schema.py --check (verify them without writing)
"""

import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

SCHEMA_DIR = Path("crates/lunco-usd/schema")
SRC = SCHEMA_DIR / "schema.usda"
OUT = SCHEMA_DIR / "generatedSchema.usda"
PLUGINFO = SCHEMA_DIR / "plugInfo.json"

# `class [Alias] "Name" (` … up to the closing `)` of the prim metadata block.
CLASS_RE = re.compile(
    r'^class\s+(?:\w+\s+)?"?(?P<name>\w+)"?\s*\((?P<meta>.*?)^\)',
    re.DOTALL | re.MULTILINE,
)


def schema_types(src: str) -> "OrderedDict[str, dict]":
    """The `Types` entry for every class in `schema.usda`, in source order.

    `bases`/`schemaKind` come from the two things the class itself declares:
    the `inherits` arc (Typed vs APISchemaBase) and, for API schemas, the
    `apiSchemaType` customData token. Nothing here is a hand-kept list.
    """
    types: "OrderedDict[str, dict]" = OrderedDict()
    for m in CLASS_RE.finditer(src):
        name, meta = m.group("name"), m.group("meta")
        if not name.startswith("LunCo"):
            continue
        if "APISchemaBase" in meta:
            api = re.search(r'apiSchemaType\s*=\s*"(\w+)"', meta)
            # USD spells the kind `singleApplyAPI` / `multipleApplyAPI`;
            # `apiSchemaType` spells it `singleApply` / `multipleApply`.
            kind = f"{(api.group(1) if api else 'singleApply')}API"
            base = "UsdAPISchemaBase"
        else:
            kind, base = "concreteTyped", "UsdTyped"
        types[name] = {
            "bases": [base],
            "autoGenerated": True,
            "schemaKind": kind,
        }
    return types


def pluginfo_text(types: "OrderedDict[str, dict]") -> str:
    """Return plugInfo with only its derived `Types` block replaced."""
    plug = json.loads(PLUGINFO.read_text(encoding="utf-8"))
    plug["Plugins"][0]["Info"]["Types"] = types
    text = json.dumps(plug, indent=4) + "\n"
    # Keep single-element `bases` on one line, as the file has always been
    # written — otherwise every regeneration reflows all 23 entries and the
    # real change (a schema added or removed) drowns in formatting churn.
    text = re.sub(r'\[\n\s*("(?:\w+)")\n\s*\]', r"[\1]", text)
    return text


def write_pluginfo(types: "OrderedDict[str, dict]") -> None:
    """Write the derived `Types` block while preserving hand-authored fields."""
    PLUGINFO.write_text(pluginfo_text(types), encoding="utf-8")
    print(f"wrote {PLUGINFO} ({len(types)} schema classes registered)")

GENERATED_HEADER = '''#usda 1.0
(
    "Generated schema for luncoSchema"
    """
    GENERATED — do not edit. Regenerate with `python3 scripts/gen_schema.py`
    after editing `schema.usda`, which is the authoritative source.

    This is the file a USD runtime actually registers (via `plugInfo.json`), and
    the file `lunco_usd::schema` parses to answer "what does this property's
    schema declare?" — its type, its variability, its UI hint, and whether it is
    `custom`.
    """
)
'''


def generated_text(src: str) -> str:
    """Return the registered USDA layer derived from the authored source."""
    # Replace the layer-metadata header (first parenthesised block after
    # `#usda 1.0`) with the GENERATED header. The source header carries the
    # authoring guide + core subLayers; neither belongs in the registered layer.
    m = re.match(r"#usda 1\.0\n\(\n.*?\n\)\n", src, flags=re.DOTALL)
    if not m:
        raise ValueError("could not find the layer metadata block in schema.usda")
    body = src[m.end():]

    # Drop `inherits = </...>` arcs (with a trailing comma if the metadata
    # list continues). Codeless registration reads flat class definitions.
    body = re.sub(r"[ \t]*(prepend\s+)?inherits\s*=\s*</[^>]*>,?\n", "", body)
    return GENERATED_HEADER + body


def main() -> int:
    check = len(sys.argv) == 2 and sys.argv[1] == "--check"
    if len(sys.argv) > 1 and not check:
        print("usage: python3 scripts/gen_schema.py [--check]", file=sys.stderr)
        return 2

    src = SRC.read_text(encoding="utf-8")
    try:
        generated = generated_text(src)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    types = schema_types(src)
    expected_pluginfo = pluginfo_text(types)

    if check:
        actual_generated = OUT.read_text(encoding="utf-8")
        actual_pluginfo = PLUGINFO.read_text(encoding="utf-8")
        stale = []
        if actual_generated != generated:
            stale.append(str(OUT))
        if actual_pluginfo != expected_pluginfo:
            stale.append(str(PLUGINFO))
        if stale:
            print("schema artifacts are stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("run `python3 scripts/gen_schema.py` to regenerate", file=sys.stderr)
            return 1
        print(f"schema artifacts in sync ({len(types)} schema classes)")
        return 0

    OUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes) from {SRC}")
    write_pluginfo(types)
    return 0


if __name__ == "__main__":
    sys.exit(main())
