//! Bakes the per-file USD metadata of every engine `*.usda` into the crate for
//! the **web build**.
//!
//! Two tables are baked (both keyed by engine-relative path — the same string
//! `lunco-assets` bakes as `asset_path`, so the wasm lookup matches):
//!
//! - `BAKED_SPAWN_META: &[(&str, bool, f32)]` — `lunco:spawnable` /
//!   `lunco:spawnLift`. Without this, web defaults every file to
//!   `spawnable = true`, so scenes/missions that opt out would wrongly appear
//!   in the spawn palette. Keeping it data-driven (no Rust folder
//!   special-casing) means the flag must travel to web as data;
//!   `discovery::list_assets` (lunco-assets) owns *which* files exist, this
//!   owns *their spawn metadata*.
//! - `BAKED_DESCRIPTIONS: &[(&str, &str)]` — `lunco:description`, the
//!   human-readable "what is this demo" string shown as a Scenarios menu
//!   tooltip. Only files that author the attribute are listed.
//!
//! `read_spawn_meta` / `read_usd_description` line-scan each USD file at
//! runtime — impossible in the browser (no filesystem). Native runtime reads
//! the description through openusd's real USDA parser
//! (`lunco_usd_bevy::read_default_prim_attr`); this build-time mirror exists
//! only so the web build (which can't parse at runtime) shows the same text.
//!
//! Build scripts run at compile time on the *host*, never on wasm, so the
//! workspace `disallowed_methods` ban on `std::fs` (a wasm-runtime foot-gun)
//! does not apply here. `clippy.toml`'s header already names `build.rs` as
//! exempt; cargo has no path-scoped lint config, so the exemption has to be
//! written out.
#![allow(clippy::disallowed_methods)]

use std::path::Path;

/// Collected per-file metadata. `description` is `None` when the file authors
/// no `lunco:description` (only scenes do today).
struct Meta {
    rel: String,
    spawnable: bool,
    lift: f32,
    description: Option<String>,
}

fn main() {
    // `<workspace>/crates/lunco-sandbox-edit` → engine library `<workspace>/assets`.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../../assets");

    let mut rows: Vec<Meta> = Vec::new();
    if assets_dir.is_dir() {
        walk(&assets_dir, &assets_dir, &mut rows);
    }
    rows.sort_by(|a, b| a.rel.cmp(&b.rel));

    // ── BAKED_SPAWN_META (format frozen — catalog::read_spawn_meta reads it) ──
    let mut spawn_src = String::from(
        "// @generated by build.rs — do not edit. (rel_path, spawnable, spawn_lift)\n\
         // for every engine `*.usda`, parsed from `lunco:spawnable`/`lunco:spawnLift`.\n\
         pub static BAKED_SPAWN_META: &[(&str, bool, f32)] = &[\n",
    );
    for m in &rows {
        spawn_src.push_str(&format!(
            "    ({:?}, {}, {}f32),\n",
            m.rel.replace('\\', "/"),
            m.spawnable,
            m.lift
        ));
    }
    spawn_src.push_str("];\n");

    // ── BAKED_DESCRIPTIONS (only files that author `lunco:description`) ──────
    let mut desc_src = String::from(
        "// @generated by build.rs — do not edit. (rel_path, description)\n\
         // for every engine `*.usda` that authors `lunco:description`.\n\
         pub static BAKED_DESCRIPTIONS: &[(&str, &str)] = &[\n",
    );
    for m in &rows {
        if let Some(d) = &m.description {
            desc_src.push_str(&format!(
                "    ({:?}, {:?}),\n",
                m.rel.replace('\\', "/"),
                d
            ));
        }
    }
    desc_src.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_spawn_meta.rs"), spawn_src).unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_descriptions.rs"), desc_src).unwrap();

    println!("cargo:rerun-if-changed={}", assets_dir.display());
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<Meta>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            match p.file_name().and_then(|s| s.to_str()) {
                Some(n) if n.starts_with('.') || n == "target" => continue,
                _ => {
                    println!("cargo:rerun-if-changed={}", p.display());
                    walk(base, &p, out);
                }
            }
        } else if p.extension().and_then(|s| s.to_str()) == Some("usda") {
            if let Ok(rel) = p.strip_prefix(base) {
                if let Some(rel_s) = rel.to_str() {
                    let (spawnable, lift, description) = parse_meta(&p);
                    out.push(Meta {
                        rel: rel_s.replace('\\', "/"),
                        spawnable,
                        lift,
                        description,
                    });
                }
            }
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
}

/// Mirror of `catalog::read_spawn_meta` + `catalog::read_usd_description`
/// (native: the openusd parser) — keep all three in sync. Reads, by a cheap
/// line scan, the three root-prim attributes a `*.usda` may author:
/// - `float lunco:spawnLift` — metres to lift the spawn point (default `0.0`).
/// - `bool  lunco:spawnable` — whether this file is a spawnable part at all
///   (default `true`); scenes set it `false` so they're not offered as
///   instances.
/// - `string lunco:description` — the demo blurb shown as a Scenarios tooltip
///   (default `None`).
fn parse_meta(path: &Path) -> (bool, f32, Option<String>) {
    let (mut spawnable, mut lift, mut description) = (true, 0.0_f32, None);
    let Ok(src) = std::fs::read_to_string(path) else { return (spawnable, lift, description) };
    for line in src.lines() {
        if let Some((_, rhs)) = line.split_once("lunco:spawnLift") {
            if let Some(v) = rhs.split('=').nth(1) {
                if let Ok(f) = v.trim().parse::<f32>() {
                    lift = f;
                }
            }
        } else if let Some((_, rhs)) = line.split_once("lunco:spawnable") {
            if let Some(v) = rhs.split('=').nth(1) {
                spawnable = v.trim().starts_with("true") || v.trim().starts_with('1');
            }
        } else if let Some((_, rhs)) = line.split_once("lunco:description") {
            description = parse_quoted(rhs);
        }
    }
    (spawnable, lift, description)
}

/// Pull the first double-quoted run out of the `= "..."` half of an authored
/// attribute line (`rhs` is the text after `lunco:description`). Mirrors the
/// string extraction openusd's parser performs natively; sufficient for the
/// plain-language prose our scenes author (no escapes / nested quotes).
fn parse_quoted(rhs: &str) -> Option<String> {
    let after_eq = rhs.split_once('=')?.1.trim();
    let rest = after_eq
        .strip_prefix('"')
        .or_else(|| after_eq.find('"').map(|i| &after_eq[i + 1..]))?;
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}
