//! Bakes the per-file USD metadata of every engine `*.usda` into the crate for
//! the **web build**.
//!
//! Two tables are baked (both keyed by engine-relative path — the same string
//! `lunco-assets` bakes as `asset_path`, so the wasm lookup matches):
//!
//! - `BAKED_SPAWN_META: &[(&str, bool, f32)]` — `lunco:spawnable` /
//!   `lunco:spawnLift`. Keeping the palette data-driven (no Rust folder
//!   special-casing) means the flag must travel to web as data;
//!   `discovery::list_assets` (lunco-assets) owns *which* files exist, this
//!   owns *their spawn metadata*.
//! - `BAKED_DESCRIPTIONS: &[(&str, &str)]` — `lunco:description`, the
//!   human-readable "what is this demo" string shown as a Scenarios menu
//!   tooltip. Only files that author the attribute are listed.
//!
//! The browser has no filesystem, so it cannot read the USD files at startup the
//! way native does — hence the bake. But the *parse* is shared, not mirrored: both
//! sides call `parse_spawn_meta` from `src/spawn_meta.rs`, which this script
//! `include!`s. It used to be a second implementation kept in sync by hand, and it
//! had already drifted (native read the description through openusd's real parser,
//! the bake through a text scan — so the two platforms could disagree about what a
//! file said about itself).
//!
//! Build scripts run at compile time on the *host*, never on wasm, so the
//! workspace `disallowed_methods` ban on `std::fs` (a wasm-runtime foot-gun)
//! does not apply here. `clippy.toml`'s header already names `build.rs` as
//! exempt; cargo has no path-scoped lint config, so the exemption has to be
//! written out.
#![allow(clippy::disallowed_methods)]

use std::path::Path;

/// Collected per-file metadata. `description` is `None` when the file authors
/// no `lunco:description` (only scenes do today).
struct Meta {
    rel: String,
    spawnable: bool,
    lift: f32,
    description: Option<String>,
}

fn main() {
    // `<workspace>/crates/lunco-sandbox-edit` → engine library `<workspace>/assets`.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../../assets");

    let mut rows: Vec<Meta> = Vec::new();
    if assets_dir.is_dir() {
        walk(&assets_dir, &assets_dir, &mut rows);
    }
    rows.sort_by(|a, b| a.rel.cmp(&b.rel));

    // ── BAKED_SPAWN_META (format frozen — catalog::read_spawn_meta reads it) ──
    let mut spawn_src = String::from(
        "// @generated by build.rs — do not edit. (rel_path, spawnable, spawn_lift)\n\
         // for every engine `*.usda`, parsed from `lunco:spawnable`/`lunco:spawnLift`.\n\
         pub static BAKED_SPAWN_META: &[(&str, bool, f32)] = &[\n",
    );
    for m in &rows {
        spawn_src.push_str(&format!(
            "    ({:?}, {}, {}f32),\n",
            m.rel.replace('\\', "/"),
            m.spawnable,
            m.lift
        ));
    }
    spawn_src.push_str("];\n");

    // ── BAKED_DESCRIPTIONS (only files that author `lunco:description`) ──────
    let mut desc_src = String::from(
        "// @generated by build.rs — do not edit. (rel_path, description)\n\
         // for every engine `*.usda` that authors `lunco:description`.\n\
         pub static BAKED_DESCRIPTIONS: &[(&str, &str)] = &[\n",
    );
    for m in &rows {
        if let Some(d) = &m.description {
            desc_src.push_str(&format!(
                "    ({:?}, {:?}),\n",
                m.rel.replace('\\', "/"),
                d
            ));
        }
    }
    desc_src.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_spawn_meta.rs"), spawn_src).unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_descriptions.rs"), desc_src).unwrap();

    println!("cargo:rerun-if-changed={}", assets_dir.display());
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<Meta>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            match p.file_name().and_then(|s| s.to_str()) {
                Some(n) if n.starts_with('.') || n == "target" => continue,
                _ => {
                    println!("cargo:rerun-if-changed={}", p.display());
                    walk(base, &p, out);
                }
            }
        } else if p.extension().and_then(|s| s.to_str()) == Some("usda") {
            if let Ok(rel) = p.strip_prefix(base) {
                if let Some(rel_s) = rel.to_str() {
                    let SpawnMeta { spawnable, lift, description } =
                        std::fs::read_to_string(&p).map(|src| parse_spawn_meta(&src)).unwrap_or_default();
                    out.push(Meta {
                        rel: rel_s.replace('\\', "/"),
                        spawnable,
                        lift,
                        description,
                    });
                }
            }
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
}

/// The ONE spawn-metadata parser, shared verbatim with the library
/// (`src/spawn_meta.rs`). A build script cannot depend on the crate it builds, so
/// it is `include!`d rather than imported — but it is the same code, which is the
/// point: the web's baked table and the native runtime read must not be two
/// implementations that "stay in sync" by discipline. They drifted before.
include!("src/spawn_meta.rs");
