//! Bakes the per-file spawn metadata (`lunco:spawnable` / `lunco:spawnLift`)
//! of every engine `*.usda` into the crate for the **web build**.
//!
//! `read_spawn_meta` line-scans each USD file at runtime — impossible in the
//! browser (no filesystem). Without this, web defaults every file to
//! `spawnable = true`, so scenes/missions that opt out (`lunco:spawnable =
//! false`) would wrongly appear in the spawn palette. Keeping it data-driven
//! (no Rust folder special-casing) means the flag must travel to web as data;
//! `discovery::list_assets` (lunco-assets) owns *which* files exist, this owns
//! *their spawn metadata*. Key is the engine-relative path — the same string
//! lunco-assets bakes as `asset_path`, so the wasm lookup matches.

use std::path::Path;

fn main() {
    // `<workspace>/crates/lunco-sandbox-edit` → engine library `<workspace>/assets`.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets_dir = Path::new(&manifest_dir).join("../../assets");

    let mut rows: Vec<(String, bool, f32)> = Vec::new();
    if assets_dir.is_dir() {
        walk(&assets_dir, &assets_dir, &mut rows);
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::from(
        "// @generated by build.rs — do not edit. (rel_path, spawnable, spawn_lift)\n\
         // for every engine `*.usda`, parsed from `lunco:spawnable`/`lunco:spawnLift`.\n\
         pub static BAKED_SPAWN_META: &[(&str, bool, f32)] = &[\n",
    );
    for (rel, spawnable, lift) in &rows {
        src.push_str(&format!(
            "    ({:?}, {}, {}f32),\n",
            rel.replace('\\', "/"),
            spawnable,
            lift
        ));
    }
    src.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    std::fs::write(Path::new(&out_dir).join("baked_spawn_meta.rs"), src).unwrap();

    println!("cargo:rerun-if-changed={}", assets_dir.display());
}

fn walk(base: &Path, dir: &Path, out: &mut Vec<(String, bool, f32)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            match p.file_name().and_then(|s| s.to_str()) {
                Some(n) if n.starts_with('.') || n == "target" => continue,
                _ => {
                    println!("cargo:rerun-if-changed={}", p.display());
                    walk(base, &p, out);
                }
            }
        } else if p.extension().and_then(|s| s.to_str()) == Some("usda") {
            if let Ok(rel) = p.strip_prefix(base) {
                if let Some(rel_s) = rel.to_str() {
                    let (spawnable, lift) = parse_meta(&p);
                    out.push((rel_s.replace('\\', "/"), spawnable, lift));
                }
            }
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
}

/// Mirror of `catalog::read_spawn_meta` — keep the two in sync.
fn parse_meta(path: &Path) -> (bool, f32) {
    let (mut spawnable, mut lift) = (true, 0.0_f32);
    let Ok(src) = std::fs::read_to_string(path) else { return (spawnable, lift) };
    for line in src.lines() {
        if let Some((_, rhs)) = line.split_once("lunco:spawnLift") {
            if let Some(v) = rhs.split('=').nth(1) {
                if let Ok(f) = v.trim().parse::<f32>() {
                    lift = f;
                }
            }
        } else if let Some((_, rhs)) = line.split_once("lunco:spawnable") {
            if let Some(v) = rhs.split('=').nth(1) {
                spawnable = v.trim().starts_with("true") || v.trim().starts_with('1');
            }
        }
    }
    (spawnable, lift)
}
